import { FormEvent, useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { Card, CardContent, CardHeader } from "../components/ui/Card";
import { Button } from "../components/ui/Button";
import { Input } from "../components/ui/Input";
import api from "../lib/api";

const stages = ["enquiry", "contacted", "visit", "application", "documents", "assessment", "accepted", "rejected", "converted"] as const;

function listData(data: any): any[] { return [data?.data, data?.students, data?.results].find(Array.isArray) ?? []; }

export default function AdmissionEnquiriesPage() {
  const client = useQueryClient(); const [search, setSearch] = useState(""); const [stage, setStage] = useState("");
  const [form, setForm] = useState({ studentName: "", guardianName: "", phone: "", email: "", source: "", classId: "", notes: "" });
  const [conversionStudent, setConversionStudent] = useState<Record<string, string>>({});
  const query = useQuery({ queryKey: ["admissions", search, stage], queryFn: async () => (await api.get(`/admissions/enquiries?${new URLSearchParams({ ...(search ? { search } : {}), ...(stage ? { stage } : {}) })}`)).data });
  const classesQuery = useQuery({ queryKey: ["classes", "admission-options"], queryFn: async () => (await api.get("/academics/classes")).data });
  const studentsQuery = useQuery({ queryKey: ["students", "admission-conversion-options"], queryFn: async () => (await api.get("/students?status=active&limit=100")).data });
  const create = useMutation({ mutationFn: async (body: any) => (await api.post("/admissions/enquiries", body)).data, onSuccess: () => { setForm({ studentName: "", guardianName: "", phone: "", email: "", source: "", classId: "", notes: "" }); client.invalidateQueries({ queryKey: ["admissions"] }); } });
  const update = useMutation({ mutationFn: async ({ id, nextStage, convertedStudentId }: any) => (await api.patch(`/admissions/enquiries/${id}`, { stage: nextStage, ...(nextStage === "converted" && convertedStudentId ? { convertedStudentId } : {}) })).data, onSuccess: () => client.invalidateQueries({ queryKey: ["admissions"] }) });
  const submit = (event: FormEvent) => { event.preventDefault(); create.mutate({ ...form, ...(form.classId ? { classId: form.classId } : {}) }); };
  const classes = listData(classesQuery.data); const students = listData(studentsQuery.data); const enquiries = Array.isArray(query.data) ? query.data : listData(query.data);

  return <div className="space-y-6"><header><p className="text-xs font-semibold uppercase tracking-[0.16em] text-slate-500">Admissions</p><h1 className="mt-1 text-2xl font-bold text-slate-950">Enquiry pipeline</h1><p className="mt-2 max-w-2xl text-sm text-slate-600">Track prospective students from first enquiry through assessment and conversion. Conversion links the enquiry to an existing student instead of creating a duplicate record.</p></header>
    <Card><CardHeader><h2 className="font-semibold text-slate-900">New enquiry</h2></CardHeader><CardContent><form onSubmit={submit} className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3"><Input required placeholder="Student name" value={form.studentName} onChange={e => setForm({ ...form, studentName: e.target.value })} /><Input required placeholder="Guardian name" value={form.guardianName} onChange={e => setForm({ ...form, guardianName: e.target.value })} /><Input placeholder="Phone" value={form.phone} onChange={e => setForm({ ...form, phone: e.target.value })} /><Input type="email" placeholder="Email" value={form.email} onChange={e => setForm({ ...form, email: e.target.value })} /><Input placeholder="Source" value={form.source} onChange={e => setForm({ ...form, source: e.target.value })} /><select aria-label="Target class" value={form.classId} onChange={e => setForm({ ...form, classId: e.target.value })} className="rounded-lg border border-slate-300 bg-white px-3 py-2 text-sm"><option value="">Target class (optional)</option>{classes.map((item: any) => <option key={item._id} value={item._id}>{item.displayName || item.name}</option>)}</select><Input placeholder="Notes" value={form.notes} onChange={e => setForm({ ...form, notes: e.target.value })} /><Button type="submit" disabled={create.isPending}>{create.isPending ? "Saving..." : "Add enquiry"}</Button></form></CardContent></Card>
    <div className="flex flex-col gap-3 sm:flex-row"><Input placeholder="Search student, guardian or phone" value={search} onChange={e => setSearch(e.target.value)} /><select value={stage} onChange={e => setStage(e.target.value)} className="rounded-lg border border-slate-300 bg-white px-3 py-2 text-sm"><option value="">All stages</option>{stages.map(item => <option key={item} value={item}>{item}</option>)}</select></div>
    <div className="grid gap-4 lg:grid-cols-2">{enquiries.map((item: any) => <Card key={item._id}><CardContent className="space-y-3 p-5"><div className="flex items-start justify-between gap-3"><div><p className="font-semibold text-slate-900">{item.studentName}</p><p className="text-sm text-slate-500">{item.guardianName}{item.phone ? ` · ${item.phone}` : ""}</p></div><span className="rounded-full bg-slate-100 px-2.5 py-1 text-xs font-bold capitalize text-slate-700">{item.stage}</span></div><div className="text-xs text-slate-500">{item.source ? `Source: ${item.source}` : "Source not recorded"}{item.followUpAt ? ` · Follow up ${new Date(item.followUpAt).toLocaleDateString()}` : ""}</div>{item.convertedStudentId && <p className="rounded-lg bg-emerald-50 px-3 py-2 text-xs font-semibold text-emerald-700">Converted to existing student: {item.convertedStudentId.firstName || item.convertedStudentId.admissionNo || item.convertedStudentId._id}</p>}<select value={item.stage} disabled={update.isPending || item.stage === "converted"} onChange={e => update.mutate({ id: item._id, nextStage: e.target.value, convertedStudentId: conversionStudent[item._id] })} className="w-full rounded-lg border border-slate-300 px-3 py-2 text-sm" aria-label={`Stage for ${item.studentName}`}>{stages.map(value => <option key={value} value={value}>{value}</option>)}</select>{item.stage !== "converted" && <p className="text-xs text-slate-500">Moving to <strong>converted</strong> requires selecting an existing active student.</p>}{item.stage !== "converted" && <select value={conversionStudent[item._id] || ""} onChange={e => setConversionStudent({ ...conversionStudent, [item._id]: e.target.value })} className="w-full rounded-lg border border-slate-300 bg-white px-3 py-2 text-sm" aria-label={`Existing student for ${item.studentName}`}><option value="">Select existing student for conversion</option>{students.map((student: any) => <option key={student._id} value={student._id}>{student.firstName} {student.lastName}{student.admissionNo ? ` · ${student.admissionNo}` : ""}</option>)}</select>}</CardContent></Card>)}</div>
    {!enquiries.length && <Card><CardContent className="py-12 text-center text-sm text-slate-500">No admission enquiries match the current filters.</CardContent></Card>}
  </div>;
}
