import {useState} from "react";
import {useMutation,useQuery,useQueryClient} from "@tanstack/react-query";
import {Button} from "../components/ui/Button";import {Input} from "../components/ui/Input";import {Select} from "../components/ui/Select";import {Card,CardContent,CardHeader} from "../components/ui/Card";import {Table} from "../components/ui/Table";import {Modal} from "../components/ui/Modal";import {Badge} from "../components/ui/Badge";import {Plus,Search,ArrowDownToLine,ArrowUpFromLine} from "lucide-react";import api from "../lib/api";
export default function InventoryPage(){const qc=useQueryClient();const[search,setSearch]=useState("");const[modal,setModal]=useState<"item"|"movement"|null>(null);const[itemId,setItemId]=useState("");const[movementType,setMovementType]=useState("stock_in");
const{data}=useQuery({queryKey:["inventory-items",search],queryFn:async()=>{const p=new URLSearchParams({page:"1",limit:"100"});if(search)p.set("search",search);return(await api.get("/inventory/items?"+p)).data}});
const{data:movements}=useQuery({queryKey:["inventory-movements"],queryFn:async()=>{return(await api.get("/inventory/movements?page=1&limit=100")).data}});
const itemMutation=useMutation({mutationFn:(d:any)=>api.post("/inventory/items",d),onSuccess:()=>{qc.invalidateQueries({queryKey:["inventory-items"]});setModal(null)}});const movementMutation=useMutation({mutationFn:(d:any)=>api.post("/inventory/movements",d),onSuccess:()=>{qc.invalidateQueries({queryKey:["inventory-items"]});qc.invalidateQueries({queryKey:["inventory-movements"]});setModal(null)}});
const columns=[{key:"itemCode",header:"Code"},{key:"name",header:"Item"},{key:"category",header:"Category",render:(x:any)=>x.category||"—"},{key:"quantity",header:"Stock",render:(x:any)=><span className={x.quantity<=x.reorderLevel?"font-semibold":""}>{x.quantity} {x.unit}</span>},{key:"status",header:"Status",render:(x:any)=><Badge variant={x.status==="active"?"success":"secondary"}>{x.status}</Badge>},{key:"actions",header:"Actions",render:(x:any)=><Button size="sm" variant="outline" onClick={()=>{setItemId(x._id);setMovementType("stock_in");setModal("movement")}}>Adjust</Button>}];
return <div className="space-y-6"><div className="flex items-center justify-between"><div><h1 className="text-2xl font-bold text-gray-900">Inventory</h1><p className="text-sm text-gray-500 mt-1">Track stock, movements and reorder levels.</p></div><Button onClick={()=>setModal("item")}><Plus className="w-4 h-4 mr-2"/>Add Item</Button></div><Card><CardHeader><div className="flex flex-wrap gap-3"><Input placeholder="Search code or item..." value={search} onChange={e=>setSearch(e.target.value)} leftIcon={<Search className="w-4 h-4"/>}/></div></CardHeader><CardContent><Table data={data?.data||[]} columns={columns} keyExtractor={x=>x._id} emptyMessage="No inventory items found."/></CardContent></Card><Card><CardHeader><h2 className="font-semibold">Recent Stock Movements</h2></CardHeader><CardContent><Table data={movements?.data||[]} columns={[{key:"type",header:"Type",render:(x:any)=><span className="flex items-center gap-2">{x.type==="stock_in"?<ArrowDownToLine className="w-4 h-4"/>:<ArrowUpFromLine className="w-4 h-4"/>}{x.type}</span>},{key:"itemId",header:"Item",render:(x:any)=>x.itemId?.name||"—"},{key:"quantity",header:"Quantity"},{key:"resultingQuantity",header:"Balance"},{key:"reason",header:"Reason",render:(x:any)=>x.reason||"—"}]} keyExtractor={x=>x._id} emptyMessage="No stock movements yet."/></CardContent></Card>
<Modal isOpen={modal==="item"} onClose={()=>setModal(null)} title="Add Inventory Item"><form className="space-y-4" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);itemMutation.mutate({itemCode:f.get("itemCode"),name:f.get("name"),category:f.get("category")||undefined,unit:f.get("unit"),reorderLevel:Number(f.get("reorderLevel")||0)})}}><Input name="itemCode" label="Item Code" required/><Input name="name" label="Name" required/><Input name="category" label="Category"/><Input name="unit" label="Unit" placeholder="piece, box, ream..." required/><Input name="reorderLevel" label="Reorder Level" type="number" min="0" defaultValue="0"/><div className="flex justify-end"><Button type="submit" disabled={itemMutation.isPending}>Create Item</Button></div></form></Modal>
<Modal isOpen={modal==="movement"} onClose={()=>setModal(null)} title="Record Stock Movement"><form className="space-y-4" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);movementMutation.mutate({itemId,type:f.get("type"),quantity:Number(f.get("quantity")),reason:f.get("reason")||undefined})}}><Select name="type" label="Movement" value={movementType} onChange={e=>setMovementType(e.target.value)}><option value="stock_in">Stock In</option><option value="stock_out">Stock Out</option><option value="adjustment">Adjustment</option></Select><Input name="quantity" label="Quantity" type="number" min="1" required/><Input name="reason" label="Reason"/><div className="flex justify-end"><Button type="submit" disabled={movementMutation.isPending}>Record Movement</Button></div></form></Modal></div>}
