import { useQuery } from "@tanstack/react-query";
import { Link, useSearchParams } from "react-router-dom";
import { Calendar, ClipboardList, CreditCard, GraduationCap, Megaphone } from "lucide-react";
import { Card, CardContent, CardHeader } from "../components/ui/Card";
import { Button } from "../components/ui/Button";
import api from "../lib/api";

export default function ParentWorkspacePage() {
  const [params, setParams] = useSearchParams();
  const childId = params.get("childId") || undefined;
  const { data, isLoading, isError, refetch } = useQuery({ queryKey: ["portal", "parent", "workspace", childId], queryFn: async () => (await api.get(`/portal/parent/workspace${childId ? `?childId=${encodeURIComponent(childId)}` : ""}`)).data });
  if (isLoading) return <p className="py-12 text-center text-sm text-slate-500">Loading your family workspace...</p>;
  if (isError) return <Card><CardContent className="py-12 text-center"><p className="font-medium text-red-600">Unable to load your child’s school information.</p><Button variant="outline" className="mt-3" onClick={() => refetch()}>Try again</Button></CardContent></Card>;
  const children = data?.children ?? []; const child = data?.selectedChild;
  if (!child) return <Card><CardContent className="py-12 text-center"><p className="font-semibold text-slate-900">No linked children</p><p className="mt-1 text-sm text-slate-500">No active student is currently linked to your account.</p></CardContent></Card>;
  const summary = data.summary;
  return <div className="space-y-6">
    <section className="relative overflow-hidden rounded-2xl bg-slate-950 p-6 text-white sm:p-8"><div className="relative z-10"><p className="text-xs font-semibold uppercase tracking-[0.18em] text-slate-300">Family workspace</p><h1 className="mt-2 text-2xl font-bold tracking-tight sm:text-3xl">Stay close to {child.firstName}’s school day.</h1><p className="mt-2 max-w-xl text-sm leading-6 text-slate-300">Attendance, homework, exams and fees for your selected child, in one place.</p></div><div className="absolute -right-12 -top-12 h-40 w-40 rotate-12 border border-white/10" aria-hidden="true" /></section>
    {children.length > 1 && <Card><CardHeader><h2 className="text-base font-semibold text-slate-900">Selected child</h2></CardHeader><CardContent><label className="sr-only" htmlFor="child-selector">Choose a child</label><select id="child-selector" value={child._id} onChange={(e) => setParams(e.target.value ? { childId: e.target.value } : {})} className="w-full rounded-lg border border-slate-300 bg-white px-3 py-2.5 text-sm text-slate-800 outline-none focus:border-primary-500 focus:ring-2 focus:ring-primary-500 sm:max-w-md">{children.map((item: any) => <option key={item._id} value={item._id}>{item.firstName} {item.lastName} · {item.classId?.displayName || "Class not assigned"}</option>)}</select></CardContent></Card>}
    <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Metric icon={Calendar} label="Attendance" value={`${summary.attendanceRate}%`} detail={`${summary.attendancePresent} of ${summary.attendanceTotal} days present`} /><Metric icon={CreditCard} label="Fee balance" value={`₹${summary.fee.balance}`} detail={summary.fee.overdue ? `₹${summary.fee.overdue} overdue` : "No overdue balance"} /><Metric icon={ClipboardList} label="Homework" value={data.upcomingHomework?.length ?? 0} detail="Due in the next 14 days" /><Metric icon={GraduationCap} label="Exams" value={data.upcomingExams?.length ?? 0} detail="Published upcoming exams" /></div>
    <div className="grid gap-6 lg:grid-cols-2"><Section icon={Calendar} title="Today’s timetable" empty="No classes scheduled today.">{data.todayClasses?.map((item: any) => <Row key={item._id} title={item.subjectId?.name || "Class"} detail={`${item.startTime || ""}${item.endTime ? `–${item.endTime}` : ""}`} />)}</Section><Section icon={ClipboardList} title="Upcoming homework" empty="No homework due soon.">{data.upcomingHomework?.map((item: any) => <Row key={item._id} title={item.title} detail={item.dueDate ? new Date(item.dueDate).toLocaleDateString() : "No due date"} />)}</Section><Section icon={GraduationCap} title="Exams" empty="No upcoming published exams.">{data.upcomingExams?.map((item: any) => <Row key={item._id} title={item.name} detail={item.startDate ? new Date(item.startDate).toLocaleDateString() : "Date pending"} />)}</Section><Section icon={Megaphone} title="Notices" empty="No current notices.">{data.notices?.map((item: any) => <Row key={item._id} title={item.title} detail={item.publishAt ? new Date(item.publishAt).toLocaleDateString() : ""} />)}</Section></div>
    <Card><CardContent className="flex flex-wrap items-center justify-between gap-3 py-4"><div><p className="font-semibold text-slate-900">Need more detail?</p><p className="text-sm text-slate-500">Open the read-only sections for {child.firstName}.</p></div><div className="flex flex-wrap gap-2"><Button asChild variant="outline"><Link to="/attendance">Attendance</Link></Button><Button asChild variant="outline"><Link to="/homework">Homework</Link></Button><Button asChild variant="outline"><Link to="/fees">Fees</Link></Button></div></CardContent></Card>
  </div>;
}
function Metric({ icon: Icon, label, value, detail }: any) { return <Card><CardContent className="p-5"><Icon className="h-5 w-5 text-primary-600" aria-hidden="true" /><p className="mt-4 text-xs font-semibold uppercase tracking-[0.12em] text-slate-500">{label}</p><p className="mt-1 text-2xl font-bold text-slate-900">{value}</p><p className="mt-1 text-xs text-slate-500">{detail}</p></CardContent></Card>; }
function Section({ icon: Icon, title, empty, children }: any) { return <Card><CardHeader><div className="flex items-center gap-2"><Icon className="h-4 w-4 text-primary-600" aria-hidden="true" /><h2 className="text-base font-semibold text-slate-900">{title}</h2></div></CardHeader><CardContent>{children?.length ? <div className="divide-y divide-slate-100">{children}</div> : <p className="py-6 text-sm text-slate-500">{empty}</p>}</CardContent></Card>; }
function Row({ title, detail }: any) { return <div className="flex items-center justify-between gap-4 py-3"><p className="min-w-0 truncate text-sm font-medium text-slate-800">{title}</p><span className="shrink-0 text-xs text-slate-500">{detail}</span></div>; }
