import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { CreditCard, IndianRupee, Receipt, Smartphone } from "lucide-react";
import { QRCodeSVG } from "qrcode.react";
import { useState } from "react";
import { useSearchParams } from "react-router-dom";
import { Card, CardContent, CardHeader } from "../components/ui/Card";
import { Badge } from "../components/ui/Badge";
import api from "../lib/api";
import { formatCurrency, formatDate } from "../utils";
import { useAuth } from "../hooks";

const statusVariant: Record<string, "success" | "warning" | "danger" | "info" | "secondary"> = { paid: "success", partial: "warning", overdue: "danger", pending: "info", waived: "secondary" };

export default function PortalFeesPage() {
  const { user } = useAuth();
  const queryClient = useQueryClient();
  const [params, setParams] = useSearchParams();
  const [payingFeeId, setPayingFeeId] = useState<string | null>(null);
  const [paymentDetails, setPaymentDetails] = useState<any>(null);
  const [utr, setUtr] = useState("");
  const [payerUpiId, setPayerUpiId] = useState("");
  const childId = params.get("childId") || "";
  const isParent = user?.role === "parent";
  const { data, isLoading, isError } = useQuery({ queryKey: ["portal-fees", user?.role, childId], queryFn: async () => (await api.get(`/portal/fees${isParent && childId ? `?childId=${encodeURIComponent(childId)}` : ""}`)).data });
  const startPayment = useMutation({ mutationFn: async (fee: any) => { const order = (await api.post("/fees/payments/orders", { feeId: fee._id, amount: fee.balance, currency: "INR", idempotencyKey: `upi-${fee._id}-${fee.balance}` })).data.order; return (await api.get(`/fees/payments/orders/${order._id}/upi`)).data; }, onSuccess: (details) => { setPaymentDetails(details); } });
  const submitPayment = useMutation({ mutationFn: async () => (await api.post(`/fees/payments/orders/${paymentDetails.order._id}/submit`, { utr: utr.trim(), payerUpiId: payerUpiId.trim() || undefined })).data, onSuccess: () => { setUtr(""); setPayerUpiId(""); queryClient.invalidateQueries({ queryKey: ["portal-fees"] }); setPaymentDetails((current: any) => current ? { ...current, submitted: true } : current); } });
  if (isLoading) return <div className="space-y-4"><div className="h-8 w-40 animate-pulse rounded bg-slate-200" /><div className="h-32 animate-pulse rounded-2xl bg-slate-200" /><div className="h-64 animate-pulse rounded-2xl bg-slate-200" /></div>;
  if (isError) return <Card><CardContent className="py-10 text-center"><p className="font-semibold">Fees are unavailable right now.</p><p className="mt-1 text-sm text-slate-500">Please try again shortly.</p></CardContent></Card>;
  const students = data?.students || []; const selectedStudentId = childId || data?.selectedStudentId || ""; const student = students.find((item: any) => item._id === selectedStudentId); const fees = data?.fees || []; const summary = data?.summary || { totalDue: 0, paid: 0, balance: 0, overdue: 0 };
  return <div className="space-y-6">
    <header><p className="text-sm font-semibold uppercase tracking-[0.16em] text-primary-600">Payments</p><h1 className="mt-1 text-2xl font-bold text-slate-950">Fees</h1><p className="mt-1 text-sm text-slate-500">View dues and pay directly to the school by UPI.</p>{student ? <p className="mt-3 text-sm font-medium text-slate-700">{student.firstName} {student.lastName} · {student.class}{student.section ? ` · ${student.section}` : ""}</p> : isParent && students.length > 1 ? <p className="mt-3 text-sm font-medium text-slate-700">All linked children</p> : null}</header>
    {isParent && students.length > 1 && <Card><CardHeader><h2 className="font-semibold">Selected child</h2></CardHeader><CardContent><label className="sr-only" htmlFor="fees-child">Choose a child</label><select id="fees-child" value={selectedStudentId} onChange={(e) => setParams(e.target.value ? { childId: e.target.value } : {})} className="w-full rounded-lg border border-slate-300 bg-white px-3 py-2.5 text-sm text-slate-800 outline-none focus:border-primary-500 focus:ring-2 focus:ring-primary-500 sm:max-w-md"><option value="">All children</option>{students.map((item: any) => <option key={item._id} value={item._id}>{item.firstName} {item.lastName} · {item.class}{item.section ? ` · ${item.section}` : ""}</option>)}</select></CardContent></Card>}
    <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{[["Total due", summary.totalDue, IndianRupee], ["Paid", summary.paid, Receipt], ["Balance", summary.balance, CreditCard], ["Overdue", summary.overdue, CreditCard]].map(([label, value, Icon]: any) => <Card key={label as string}><CardContent className="flex items-center gap-3 p-5"><div className="rounded-xl bg-slate-100 p-2.5"><Icon className="h-5 w-5 text-slate-600" aria-hidden="true" /></div><div><p className="text-xs font-semibold uppercase tracking-wide text-slate-500">{label}</p><p className="mt-1 text-xl font-bold text-slate-950">{formatCurrency(value)}</p></div></CardContent></Card>)}</div>
    {fees.length === 0 ? <Card><CardContent className="py-12 text-center"><CreditCard className="mx-auto h-10 w-10 text-slate-300" /><p className="mt-3 font-semibold">No fee records yet</p><p className="mt-1 text-sm text-slate-500">Fee records will appear here when the school publishes them.</p></CardContent></Card> : <Card><CardHeader><h2 className="font-semibold">Fee records</h2></CardHeader><CardContent><div className="divide-y divide-slate-100">{fees.map((fee: any) => <div key={fee._id} className="grid gap-3 py-4 sm:grid-cols-[1fr_auto] sm:items-center"><div><div className="flex flex-wrap items-center gap-2"><p className="font-semibold text-slate-900 capitalize">{fee.feeType || "Fee"}</p><Badge variant={statusVariant[fee.status] || "secondary"}>{fee.status}</Badge></div><p className="mt-1 text-sm text-slate-500">{fee.academicYear || "Academic year"}{fee.dueDate ? ` · Due ${formatDate(fee.dueDate)}` : ""}</p></div><div className="text-left sm:text-right"><p className="font-bold text-slate-900">{formatCurrency(fee.balance)}</p><p className="text-xs text-slate-500">of {formatCurrency(fee.totalDue)} remaining</p>{fee.balance > 0 && <button type="button" onClick={() => { setPayingFeeId(fee._id); setPaymentDetails(null); startPayment.mutate(fee); }} disabled={startPayment.isPending && payingFeeId === fee._id} className="mt-2 inline-flex items-center gap-2 rounded-lg bg-primary-600 px-3 py-2 text-xs font-semibold text-white disabled:opacity-60"><Smartphone className="h-4 w-4" />{startPayment.isPending && payingFeeId === fee._id ? "Preparing UPI…" : "Pay by UPI"}</button>}</div></div>)}</div></CardContent></Card>}
    {paymentDetails && <Card><CardHeader><h2 className="font-semibold">Pay school fee by UPI</h2><p className="text-sm text-slate-500">Scan the QR with any UPI app, pay the exact amount, then submit the UTR.</p></CardHeader><CardContent className="grid gap-6 md:grid-cols-[auto_1fr] md:items-start"><div className="rounded-2xl border border-slate-200 bg-white p-4"><QRCodeSVG value={paymentDetails.upiUrl} size={220} includeMargin /></div><div className="space-y-4"><div><p className="text-sm text-slate-500">Pay to</p><p className="font-semibold">{paymentDetails.payee.name}</p><p className="text-sm text-slate-600">{paymentDetails.payee.upiVpa}</p><p className="mt-2 text-2xl font-bold">{formatCurrency(paymentDetails.order.amount)}</p></div>{paymentDetails.submitted ? <div className="rounded-xl bg-amber-50 p-4 text-sm text-amber-800">UTR submitted successfully. The school will verify the payment against its bank statement.</div> : <form onSubmit={(event) => { event.preventDefault(); submitPayment.mutate(); }} className="space-y-3"><label className="block text-sm font-medium text-slate-700">UTR / transaction reference<input value={utr} onChange={(e) => setUtr(e.target.value)} required minLength={6} maxLength={35} className="mt-1 w-full rounded-lg border border-slate-300 px-3 py-2.5" placeholder="Enter UTR after payment" /></label><label className="block text-sm font-medium text-slate-700">Your UPI ID <span className="font-normal text-slate-400">(optional)</span><input value={payerUpiId} onChange={(e) => setPayerUpiId(e.target.value)} maxLength={255} className="mt-1 w-full rounded-lg border border-slate-300 px-3 py-2.5" placeholder="name@upi" /></label><button type="submit" disabled={submitPayment.isPending || !utr.trim()} className="w-full rounded-lg bg-slate-900 px-4 py-2.5 text-sm font-semibold text-white disabled:opacity-60">{submitPayment.isPending ? "Submitting…" : "Submit payment for verification"}</button></form>}</div></CardContent></Card>}
    <p className="text-xs text-slate-400">UPI payments are verified by the school. No payment gateway is used.</p>
  </div>;
}
