import { useQuery } from "@tanstack/react-query";
import { Link } from "react-router-dom";
import { CheckCircle2, ClipboardList, CreditCard, Megaphone, UserRound, Trophy } from "lucide-react";
import { Card, CardContent, CardHeader } from "../components/ui/Card";
import api from "../lib/api";
import { useAuth } from "../hooks";

export default function StudentWorkspacePage() {
  const { user } = useAuth();
  const { data, isLoading, isError, refetch } = useQuery({ queryKey: ["portal", "student", "workspace"], queryFn: async () => (await api.get("/portal/student/workspace")).data, enabled: Boolean(user) });
  if (isLoading) return <div className="rounded-2xl border bg-white p-8 text-center text-sm text-slate-500">Loading your school day...</div>;
  if (isError) return <div className="rounded-2xl border border-red-200 bg-red-50 p-6 text-sm text-red-700">Unable to load your student workspace. <button type="button" className="font-semibold underline" onClick={() => refetch()}>Try again</button></div>;
  const student = data?.student;
  const fee = data?.fees?.summary;
  const latest = data?.latestResults?.[0];
  return <div className="space-y-6">
    <header className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between">
      <div><p className="text-xs font-semibold uppercase tracking-[0.16em] text-primary-600">Student workspace</p><h1 className="mt-2 text-2xl font-bold tracking-tight text-slate-900">Good day, {student?.firstName || "student"}</h1><p className="mt-1 text-sm text-slate-500">{student?.classId?.displayName || "Class not assigned"}{student?.sectionId?.name ? ` · ${student.sectionId.name}` : ""} · {data?.academicYear?.name || "Current academic year"}</p></div>
      {student?._id && <Link to={`/students/${student._id}`} className="inline-flex w-fit items-center gap-2 rounded-lg border border-slate-300 bg-white px-3 py-2 text-sm font-semibold text-slate-700 hover:bg-slate-50 focus:outline-none focus-visible:ring-2 focus-visible:ring-primary-500 focus-visible:ring-offset-2"><UserRound className="h-4 w-4" aria-hidden="true" />View profile</Link>}
    </header>
    <section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4" aria-label="Your key numbers"><Stat label="Attendance" value={`${data?.summary?.attendanceRate ?? 0}%`} icon={CheckCircle2}/><Stat label="Homework due" value={data?.upcomingHomework?.length ?? 0} icon={ClipboardList}/><Stat label="Fee balance" value={`₹${Number(fee?.balance ?? 0).toLocaleString("en-IN")}`} icon={CreditCard}/><Stat label="Latest result" value={latest ? `${latest.percentage}%` : "—"} icon={Trophy}/></section>
    <div className="grid gap-6 xl:grid-cols-[1.2fr_0.8fr]">
      <Card><CardHeader><h2 className="text-base font-semibold text-slate-900">Today&apos;s timetable</h2></CardHeader><CardContent>{data?.todayClasses?.length ? <div className="space-y-2">{data.todayClasses.map((item: any, index: number) => <div key={`${item._id || index}`} className="flex items-start justify-between gap-4 rounded-xl bg-slate-50 px-4 py-3"><div><p className="text-sm font-semibold text-slate-800">{item.subjectId?.name || "Subject"}</p><p className="text-xs text-slate-500">{item.teacherId ? `${item.teacherId.firstName || ""} ${item.teacherId.lastName || ""}`.trim() : "Teacher"}{item.sectionId?.name ? ` · ${item.sectionId.name}` : ""}</p></div><p className="shrink-0 text-xs font-semibold text-slate-600">{item.startTime}–{item.endTime}</p></div>)}</div> : <Empty text="No classes are scheduled today." />}</CardContent></Card>
      <Card><CardHeader><h2 className="text-base font-semibold text-slate-900">Upcoming homework</h2></CardHeader><CardContent>{data?.upcomingHomework?.length ? <List items={data.upcomingHomework.slice(0, 5).map((item: any) => `${item.subjectId?.name || "Subject"} · ${item.title}`)} /> : <Empty text="You are all caught up." />}</CardContent></Card>
      <Card><CardHeader><h2 className="text-base font-semibold text-slate-900">Attendance</h2></CardHeader><CardContent><div className="flex items-center justify-between"><div><p className="text-3xl font-bold text-slate-900">{data?.summary?.attendanceRate ?? 0}%</p><p className="mt-1 text-sm text-slate-500">{data?.summary?.attendancePresent ?? 0} present days out of {data?.summary?.attendanceTotal ?? 0}</p></div><CheckCircle2 className="h-8 w-8 text-primary-600" aria-hidden="true" /></div><div className="mt-5 space-y-2">{(data?.recentAttendance ?? []).slice(0, 5).map((row: any) => <div key={String(row._id)} className="flex justify-between text-sm"><span className="text-slate-600">{new Date(row.date).toLocaleDateString()}</span><span className="font-semibold text-slate-800">{row.records?.find((record: any) => String(record.studentId) === String(student?._id))?.status || "—"}</span></div>)}</div></CardContent></Card>
      <Card><CardHeader><h2 className="text-base font-semibold text-slate-900">Results & fees</h2></CardHeader><CardContent><div className="space-y-4"><div><p className="text-xs font-semibold uppercase tracking-wide text-slate-500">Latest result</p>{latest ? <p className="mt-1 text-sm text-slate-700">{latest.examId?.name || "Published exam"} · {latest.percentage}% · Grade {latest.grade}</p> : <Empty text="No published results yet." />}</div><div><p className="text-xs font-semibold uppercase tracking-wide text-slate-500">Fee balance</p><p className="mt-1 text-xl font-bold text-slate-900">₹{Number(fee?.balance ?? 0).toLocaleString("en-IN")}</p><p className="text-xs text-slate-500">Paid ₹{Number(fee?.paid ?? 0).toLocaleString("en-IN")} of ₹{Number(fee?.totalDue ?? 0).toLocaleString("en-IN")}</p></div></div></CardContent></Card>
      <Card className="xl:col-span-2"><CardHeader><div className="flex items-center gap-2"><Megaphone className="h-4 w-4 text-primary-600" aria-hidden="true"/><h2 className="text-base font-semibold text-slate-900">Important notices</h2></div></CardHeader><CardContent>{data?.notices?.length ? <List items={data.notices.map((item: any) => item.title)} /> : <Empty text="No current notices." />}</CardContent></Card>
    </div>
  </div>;
}
function Stat({ label, value, icon: Icon }: { label: string; value: string | number; icon: any }) { return <Card><CardHeader><div className="flex items-center justify-between"><p className="text-xs font-semibold uppercase tracking-wide text-slate-500">{label}</p><Icon className="h-4 w-4 text-primary-600" aria-hidden="true" /></div></CardHeader><CardContent><p className="text-3xl font-bold text-slate-900">{value}</p></CardContent></Card>; }
function List({ items }: { items: string[] }) { return <ul className="divide-y divide-slate-100">{items.map((item, index) => <li key={`${item}-${index}`} className="py-3 text-sm text-slate-700">{item}</li>)}</ul>; }
function Empty({ text }: { text: string }) { return <p className="py-2 text-sm text-slate-500">{text}</p>; }
