import { useEffect, useState } from "react";
import api from "../lib/api";
import { Button } from "../components/ui/button";
import { Input } from "../components/ui/input";
import { Textarea } from "../components/ui/textarea";

type Student={_id:string;firstName:string;lastName:string;admissionNo:string};
type Behaviour={_id:string;studentId:string;kind:string;category:string;severity:string;occurredAt:string;description:string;actionTaken?:string;status:string;parentAcknowledgedAt?:string};
export default function StudentBehaviourPage(){
 const [students,setStudents]=useState<Student[]>([]); const [rows,setRows]=useState<Behaviour[]>([]); const [studentId,setStudentId]=useState(""); const [kind,setKind]=useState("incident"); const [category,setCategory]=useState(""); const [severity,setSeverity]=useState("low"); const [description,setDescription]=useState(""); const [actionTaken,setActionTaken]=useState(""); const [error,setError]=useState(""); const [busy,setBusy]=useState(false);
 const load=async()=>{try{const q=studentId?`?studentId=${studentId}&limit=50`:"?limit=50";const r=await api.get(`/behaviour${q}`);setRows(r.data||[]);}catch(e:any){setError(e?.response?.data?.message||"Unable to load behaviour records");}};
 useEffect(()=>{api.get("/students?status=active&limit=100").then(r=>setStudents(r.data?.students||r.data?.data||[])).catch(()=>{});},[]); useEffect(()=>{load();},[studentId]);
 const submit=async()=>{setError("");if(!studentId||!category||!description){setError("Student, category and description are required");return;}setBusy(true);try{await api.post("/behaviour",{studentId,kind,category,severity,occurredAt:new Date().toISOString(),description,actionTaken:actionTaken||undefined});setCategory("");setDescription("");setActionTaken("");await load();}catch(e:any){setError(e?.response?.data?.message||"Unable to save record");}finally{setBusy(false);}};
 const resolve=async(id:string)=>{try{await api.patch(`/behaviour/${id}`,{status:"resolved"});await load();}catch(e:any){setError(e?.response?.data?.message||"Unable to update record");}};
 return <main className="space-y-5 p-4 md:p-6"><header><h1 className="text-2xl font-semibold">Behaviour & Discipline</h1><p className="text-sm text-muted-foreground">Record incidents and positive recognition with an auditable, school-scoped workflow.</p></header>
 <section className="grid gap-4 rounded-2xl border bg-card p-4 md:grid-cols-2"><div className="space-y-3"><select className="h-10 w-full rounded-md border bg-background px-3 text-sm" value={studentId} onChange={e=>setStudentId(e.target.value)}><option value="">Select student</option>{students.map(s=><option key={s._id} value={s._id}>{s.firstName} {s.lastName} · {s.admissionNo}</option>)}</select><div className="grid grid-cols-2 gap-3"><select className="h-10 rounded-md border bg-background px-3 text-sm" value={kind} onChange={e=>setKind(e.target.value)}><option value="incident">Incident</option><option value="recognition">Recognition</option></select><select className="h-10 rounded-md border bg-background px-3 text-sm" value={severity} onChange={e=>setSeverity(e.target.value)}><option value="low">Low</option><option value="medium">Medium</option><option value="high">High</option></select></div><Input placeholder="Category (e.g. attendance, conduct, achievement)" value={category} onChange={e=>setCategory(e.target.value)}/><Textarea placeholder="Short description" value={description} onChange={e=>setDescription(e.target.value)}/><Textarea placeholder="Action taken (optional)" value={actionTaken} onChange={e=>setActionTaken(e.target.value)}/><Button onClick={submit} disabled={busy}>{busy?"Saving…":"Record behaviour"}</Button>{error&&<p className="text-sm text-destructive">{error}</p>}</div>
 <div><h2 className="mb-3 font-medium">Recent records</h2><div className="space-y-2">{rows.map(r=><article key={r._id} className="rounded-xl border p-3"><div className="flex flex-wrap items-center justify-between gap-2"><div className="font-medium capitalize">{r.kind} · {r.category}</div><span className="text-xs capitalize text-muted-foreground">{r.severity} · {r.status}</span></div><p className="mt-1 text-sm">{r.description}</p><div className="mt-2 flex items-center justify-between text-xs text-muted-foreground"><span>{new Date(r.occurredAt).toLocaleDateString()}</span>{r.status==="open"&&<Button size="sm" variant="outline" onClick={()=>resolve(r._id)}>Resolve</Button>}</div></article>)}{!rows.length&&<p className="text-sm text-muted-foreground">No behaviour records.</p>}</div></div></section></main>;
}
