import { Router } from "express";
import { authenticate, requirePermission, requireAnyPermission, validate } from "../middleware/index.js";
import { getExams, getExamById, createExam, updateExam, publishExam, upsertMarks, correctResult, getResults, getResultById } from "../controllers/examController.js";
import { CreateExamSchema, UpdateExamSchema, MarksEntrySchema, ResultCorrectionSchema, ExamQuerySchema, ResultQuerySchema, IdParamSchema } from "../validators/index.js";
const router = Router();
router.use(authenticate);
router.get("/", requireAnyPermission("exams:read", "marks:read", "results:read", "results:read:own", "results:read:child"), validate(ExamQuerySchema,"query"), getExams);
router.get("/:id", requireAnyPermission("exams:read", "marks:read", "results:read", "results:read:own", "results:read:child"), validate(IdParamSchema,"params"), getExamById);
router.post("/", requirePermission("exams:write"), validate(CreateExamSchema), createExam);
router.patch("/:id", requirePermission("exams:write"), validate(IdParamSchema,"params"), validate(UpdateExamSchema), updateExam);
router.post("/:id/publish", requirePermission("exams:publish"), validate(IdParamSchema,"params"), publishExam);
router.put("/:id/results", requirePermission("marks:write"), validate(IdParamSchema,"params"), validate(MarksEntrySchema), upsertMarks);
router.patch("/:id/results/correct", requirePermission("marks:correct"), validate(IdParamSchema,"params"), validate(ResultCorrectionSchema), correctResult);
router.get("/results/list", requireAnyPermission("marks:read","results:read","results:read:own","results:read:child"), validate(ResultQuerySchema,"query"), getResults);
router.get("/results/:id", requireAnyPermission("marks:read","results:read","results:read:own","results:read:child"), validate(IdParamSchema,"params"), getResultById);
export default router;
