import { Router } from "express";
import authRoutes from "./authRoutes.js";
import studentRoutes from "./studentRoutes.js";
import teacherRoutes from "./teacherRoutes.js";
import staffRoutes from "./staffRoutes.js";
import libraryRoutes from "./libraryRoutes.js";
import transportRoutes from "./transportRoutes.js";
import inventoryRoutes from "./inventoryRoutes.js";
import classRoutes from "./classRoutes.js";
import attendanceRoutes from "./attendanceRoutes.js";
import feeRoutes from "./feeRoutes.js";
import dashboardRoutes from "./dashboardRoutes.js";
import analyticsRoutes from "./analyticsRoutes.js";
import parentRoutes from "./parentRoutes.js";
import schoolRoutes from "./schoolRoutes.js";
import settingsRoutes from "./settingsRoutes.js";
import auditLogRoutes from "./auditLogRoutes.js";
import academicYearRoutes from "./academicYearRoutes.js";
import examRoutes from "./examRoutes.js";
import homeworkRoutes from "./homeworkRoutes.js";
import noticeRoutes from "./noticeRoutes.js";
import timetableRoutes from "./timetableRoutes.js";
import portalRoutes from "./portalRoutes.js";
import notificationRoutes from "./notificationRoutes.js";
import reportRoutes from "./reportRoutes.js";
import platformTenantRoutes from "./platformTenantRoutes.js";
import platformOperationsRoutes from "./platformOperationsRoutes.js";
import moduleEntitlementRoutes from "./moduleEntitlementRoutes.js";
import billingRoutes from "./billingRoutes.js";
import saasInvoiceRoutes from "./saasInvoiceRoutes.js";
import supportAccessRoutes from "./supportAccessRoutes.js";
import tenantUsageRoutes from "./tenantUsageRoutes.js";
import { authenticate } from "../middleware/auth.js";
import { requireModule } from "../middleware/moduleEntitlement.js";

const router = Router();
router.use("/auth", authRoutes);
router.use("/modules", moduleEntitlementRoutes);
router.use("/students", authenticate, requireModule("students"), studentRoutes);
router.use("/teachers", authenticate, requireModule("teachers"), teacherRoutes);
router.use("/staff", authenticate, requireModule("staff"), staffRoutes);
router.use("/library", authenticate, requireModule("library"), libraryRoutes);
router.use("/transport", authenticate, requireModule("transport"), transportRoutes);
router.use("/inventory", authenticate, requireModule("inventory"), inventoryRoutes);
router.use("/academics", authenticate, requireModule("academics"), classRoutes);
router.use("/attendance", authenticate, requireModule("attendance"), attendanceRoutes);
router.use("/fees", authenticate, requireModule("fees"), feeRoutes);
router.use("/dashboard", authenticate, requireModule("dashboard"), dashboardRoutes);
router.use("/analytics", analyticsRoutes);
router.use("/parents", authenticate, requireModule("parents"), parentRoutes);
router.use("/school", authenticate, requireModule("school"), schoolRoutes);
router.use("/settings", settingsRoutes);
router.use("/academic-years", authenticate, requireModule("academicYears"), academicYearRoutes);
router.use("/reports", reportRoutes);
router.use("/audit-logs", auditLogRoutes);
router.use("/exams", authenticate, requireModule("exams"), examRoutes);
router.use("/homework", authenticate, requireModule("homework"), homeworkRoutes);
router.use("/notices", authenticate, requireModule("notices"), noticeRoutes);
router.use("/timetable", authenticate, requireModule("timetable"), timetableRoutes);
router.use("/portal", authenticate, requireModule("portal"), portalRoutes);
router.use("/notifications", authenticate, requireModule("notifications"), notificationRoutes);
router.use("/platform", platformTenantRoutes);
router.use("/platform", platformOperationsRoutes);
router.use("/platform/billing", billingRoutes);
router.use("/platform/usage", tenantUsageRoutes);
router.use("/billing", saasInvoiceRoutes);
router.use("/support", supportAccessRoutes);
router.get("/health", (req, res) => res.json({ status: "ok", timestamp: new Date().toISOString() }));

export default router;
