import { Router } from "express";
import authRoutes from "./authRoutes.js";
import studentRoutes from "./studentRoutes.js";
import teacherRoutes from "./teacherRoutes.js";
import classRoutes from "./classRoutes.js";
import attendanceRoutes from "./attendanceRoutes.js";
import feeRoutes from "./feeRoutes.js";
import dashboardRoutes from "./dashboardRoutes.js";
import parentRoutes from "./parentRoutes.js";
import schoolRoutes from "./schoolRoutes.js";
import auditLogRoutes from "./auditLogRoutes.js";
import academicYearRoutes from "./academicYearRoutes.js";
import examRoutes from "./examRoutes.js";
import homeworkRoutes from "./homeworkRoutes.js";
const router = Router();
router.use("/auth", authRoutes); router.use("/students", studentRoutes); router.use("/teachers", teacherRoutes); router.use("/academics", classRoutes); router.use("/attendance", attendanceRoutes); router.use("/fees", feeRoutes); router.use("/dashboard", dashboardRoutes); router.use("/parents", parentRoutes); router.use("/school", schoolRoutes); router.use("/academic-years", academicYearRoutes); router.use("/audit-logs", auditLogRoutes); router.use("/exams", examRoutes); router.use("/homework", homeworkRoutes);
router.get("/health", (req, res) => res.json({ status: "ok", timestamp: new Date().toISOString() }));
export default router;
