import { Router } from "express";
import { authenticate, requireAnyPermission, requirePermission, validate } from "../middleware/index.js";
import { getNotifications, markAllNotificationsRead, markNotificationRead, getNotificationPreferences, upsertNotificationPreference, getNotificationDeliveryAttempts } from "../controllers/notificationController.js";
import { listNotificationTemplates, upsertNotificationTemplate, archiveNotificationTemplate } from "../controllers/notificationTemplateController.js";
import { IdParamSchema } from "../validators/index.js";
import { NotificationPreferenceSchema, NotificationQuerySchema } from "@school-erp/shared";
import { NotificationTemplateSchema } from "../validators/notificationTemplate.js";

const router = Router();
const notificationPermissions = ["notices:read", "notices:read:own", "notices:read:child"];
router.use(authenticate);
router.get("/", requireAnyPermission(...notificationPermissions), validate(NotificationQuerySchema, "query"), getNotifications);
router.patch("/:id/read", requireAnyPermission(...notificationPermissions), validate(IdParamSchema, "params"), markNotificationRead);
router.post("/read-all", requireAnyPermission(...notificationPermissions), markAllNotificationsRead);
router.get("/preferences", requireAnyPermission(...notificationPermissions), getNotificationPreferences);
router.put("/preferences", requireAnyPermission(...notificationPermissions), validate(NotificationPreferenceSchema), upsertNotificationPreference);
router.get("/delivery-attempts", requireAnyPermission("audit:read"), getNotificationDeliveryAttempts);
router.get("/templates", requirePermission("notices:read"), listNotificationTemplates);
router.put("/templates", requirePermission("notices:write"), validate(NotificationTemplateSchema), upsertNotificationTemplate);
router.delete("/templates/:id", requirePermission("notices:write"), validate(IdParamSchema, "params"), archiveNotificationTemplate);
export default router;
