import { Request, Response, NextFunction } from "express";
import mongoose from "mongoose";
import { Exam, ExamResult, AcademicYear, Class, Subject, Student, Teacher } from "../models/index.js";
import { AppError } from "../utils/errors.js";
import { getTenantId } from "../utils/tenant.js";
import { createAuditLog } from "../services/auditLog.js";
import { UserRole } from "@school-erp/shared";

function examFilter(req: Request, extra: Record<string, unknown> = {}) { return { schoolId: getTenantId(req), ...extra }; }
async function assertTeacherCanMark(req: Request, exam: any, subjectIds: string[]) {
  if (req.user!.role !== UserRole.TEACHER) return;
  const teacher = await Teacher.findOne({ userId: req.user!.userId, schoolId: getTenantId(req) }).select("subjects classTeacherOf").lean();
  if (!teacher) throw AppError.forbidden("Teacher profile not found");
  const classAllowed = teacher.classTeacherOf?.some((id: any) => id.toString() === exam.classId.toString());
  const subjectsAllowed = subjectIds.every((id) => teacher.subjects?.some((s: any) => s.toString() === id));
  if (!classAllowed && !subjectsAllowed) throw AppError.forbidden("You are not assigned to this exam class or subject");
  if (!subjectsAllowed) throw AppError.forbidden("You can only enter marks for subjects assigned to you");
}
function calculate(exam: any, marks: Array<{subjectId: string; value: number; absent?: boolean}>) {
  const bySubject = new Map(exam.subjects.map((s: any) => [s.subjectId.toString(), s]));
  if (marks.length !== exam.subjects.length) throw AppError.badRequest("Marks must be supplied for every exam subject");
  const seen = new Set<string>(); let total = 0; let obtained = 0; let passed = true;
  for (const mark of marks) {
    if (seen.has(mark.subjectId)) throw AppError.badRequest("Duplicate subject marks"); seen.add(mark.subjectId);
    const config: any = bySubject.get(mark.subjectId); if (!config) throw AppError.badRequest("Subject is not part of this exam");
    if (mark.value > config.maxMarks) throw AppError.badRequest(`Marks cannot exceed ${config.maxMarks} for this subject`);
    if (mark.absent && mark.value !== 0) throw AppError.badRequest("Absent marks must be zero");
    total += config.maxMarks; obtained += mark.value; if (mark.value < config.passMarks) passed = false;
  }
  const percentage = total ? Math.round((obtained / total) * 10000) / 100 : 0;
  const rule = [...exam.gradeRules].sort((a: any,b: any)=>b.minPercentage-a.minPercentage).find((r: any)=>percentage >= r.minPercentage && percentage <= r.maxPercentage);
  if (!rule) throw AppError.badRequest("No grade rule matches the calculated percentage");
  return { totalMarks: total, obtainedMarks: obtained, percentage, grade: rule.grade, result: passed ? "pass" : "fail" };
}

export async function getExams(req: Request, res: Response, next: NextFunction) { try { const q=req.validatedQuery as any; const filter=examFilter(req); if(q.academicYearId) filter.academicYearId=q.academicYearId; if(q.classId) filter.classId=q.classId; if(q.status) filter.status=q.status; const skip=(q.page-1)*q.limit; const [data,total]=await Promise.all([Exam.find(filter).populate("academicYearId classId subjects.subjectId").sort({startDate:-1,createdAt:-1}).skip(skip).limit(q.limit).lean(),Exam.countDocuments(filter)]); res.json({data,pagination:{page:q.page,limit:q.limit,total,totalPages:Math.ceil(total/q.limit)}}); } catch(e){next(e);} }
export async function getExamById(req: Request,res: Response,next: NextFunction){try{const exam=await Exam.findOne(examFilter(req,{_id:req.validatedParams.id})).populate("academicYearId classId subjects.subjectId");if(!exam)throw AppError.notFound("Exam not found");res.json({exam});}catch(e){next(e);}}
export async function createExam(req: Request,res: Response,next: NextFunction){try{const d=req.validatedBody as any; const schoolId=getTenantId(req); const [year,klass]=await Promise.all([AcademicYear.findOne({_id:d.academicYearId,schoolId}),Class.findOne({_id:d.classId,schoolId})]); if(!year||!klass)throw AppError.badRequest("Academic year and class must belong to this school"); const subjectIds=d.subjects.map((s:any)=>s.subjectId); const subjects=await Subject.find({_id:{$in:subjectIds},schoolId,classIds:d.classId}).select("_id").lean(); if(subjects.length!==subjectIds.length)throw AppError.badRequest("Every exam subject must belong to this school and class"); const existing=await Exam.findOne({schoolId,academicYearId:d.academicYearId,classId:d.classId,name:d.name}); if(existing)throw AppError.conflict("An exam with this name already exists for this class and academic year"); const exam=await Exam.create({...d,schoolId,status:"draft"}); await createAuditLog({userId:req.user!.userId,action:"CREATE",entity:"Exam",entityId:exam._id.toString(),after:{name:exam.name,classId:exam.classId.toString(),academicYearId:exam.academicYearId.toString()}}); res.status(201).json({exam});}catch(e){next(e);}}
export async function updateExam(req: Request,res: Response,next: NextFunction){try{const id=req.validatedParams.id; const exam=await Exam.findOne(examFilter(req,{_id:id}));if(!exam)throw AppError.notFound("Exam not found");if(exam.status==="published")throw AppError.conflict("Published exams cannot be edited; create a correction through the results workflow"); const d=req.validatedBody as any; const schoolId=getTenantId(req); if(d.academicYearId||d.classId){const [year,klass]=await Promise.all([AcademicYear.findOne({_id:d.academicYearId??exam.academicYearId,schoolId}),Class.findOne({_id:d.classId??exam.classId,schoolId})]);if(!year||!klass)throw AppError.badRequest("Academic year and class must belong to this school");} if(d.subjects){const ids=d.subjects.map((s:any)=>s.subjectId);const subjects=await Subject.find({_id:{$in:ids},schoolId,classIds:d.classId??exam.classId}).select("_id").lean();if(subjects.length!==ids.length)throw AppError.badRequest("Every exam subject must belong to this school and class");} Object.assign(exam,d);await exam.save();await createAuditLog({userId:req.user!.userId,action:"UPDATE",entity:"Exam",entityId:id,after:d});res.json({exam});}catch(e){next(e);}}
export async function publishExam(req: Request,res: Response,next: NextFunction){try{const exam=await Exam.findOne(examFilter(req,{_id:req.validatedParams.id}));if(!exam)throw AppError.notFound("Exam not found");if(exam.status==="published")return res.json({exam,message:"Exam is already published"}); const resultCount=await ExamResult.countDocuments({schoolId:getTenantId(req),examId:exam._id}); if(!resultCount)throw AppError.badRequest("Enter at least one student result before publishing"); exam.status="published";exam.publishedAt=new Date();exam.publishedBy=new mongoose.Types.ObjectId(req.user!.userId);await exam.save(); await ExamResult.updateMany({schoolId:getTenantId(req),examId:exam._id},{status:"published",publishedAt:exam.publishedAt,publishedBy:exam.publishedBy});await createAuditLog({userId:req.user!.userId,action:"PUBLISH",entity:"Exam",entityId:exam._id.toString(),after:{status:"published",resultCount}});res.json({exam});}catch(e){next(e);}}

export async function upsertMarks(req: Request,res: Response,next: NextFunction){try{const exam=await Exam.findOne(examFilter(req,{_id:req.validatedParams.id}));if(!exam)throw AppError.notFound("Exam not found");if(exam.status==="published")throw AppError.conflict("Published exam marks cannot be changed through marks entry");const d=req.validatedBody as any;const student=await Student.findOne({_id:d.studentId,schoolId:getTenantId(req),classId:exam.classId}).lean();if(!student)throw AppError.badRequest("Student must belong to the exam class and school");await assertTeacherCanMark(req,exam,d.marks.map((m:any)=>m.subjectId));const calculated=calculate(exam,d.marks);const previous=await ExamResult.findOne({schoolId:getTenantId(req),examId:exam._id,studentId:student._id}).lean();const result=await ExamResult.findOneAndUpdate({schoolId:getTenantId(req),examId:exam._id,studentId:student._id},{schoolId:getTenantId(req),examId:exam._id,studentId:student._id,classId:student.classId,sectionId:student.sectionId,academicYearId:exam.academicYearId,marks:d.marks,...calculated,status:"draft"},{upsert:true,new:true,setDefaultsOnInsert:true});await createAuditLog({userId:req.user!.userId,action:previous?"UPDATE":"CREATE",entity:"ExamResult",entityId:result._id.toString(),before:previous?{marks:previous.marks,percentage:previous.percentage,grade:previous.grade}:undefined,after:{marks:result.marks,percentage:result.percentage,grade:result.grade}});res.json({result});}catch(e){next(e);}}

export async function correctResult(req: Request,res: Response,next: NextFunction){try{const d=req.validatedBody as any;const exam=await Exam.findOne(examFilter(req,{_id:req.validatedParams.id}));if(!exam)throw AppError.notFound("Exam not found");if(exam.status!=="published")throw AppError.badRequest("Corrections are available only after publishing");const result=await ExamResult.findOne(examFilter(req,{examId:exam._id,studentId:d.studentId}));if(!result)throw AppError.notFound("Student result not found");const subjectConfig=exam.subjects.find((s:any)=>s.subjectId.toString()===d.subjectId);if(!subjectConfig)throw AppError.badRequest("Subject is not part of this exam");if(d.value>subjectConfig.maxMarks)throw AppError.badRequest("Marks exceed subject maximum");if(d.absent&&d.value!==0)throw AppError.badRequest("Absent marks must be zero");const before={marks:result.marks,obtainedMarks:result.obtainedMarks,percentage:result.percentage,grade:result.grade,result:result.result};const marks=result.marks.map((m:any)=>m.subjectId.toString()===d.subjectId?{subjectId:m.subjectId,value:d.value,absent:d.absent}:m);Object.assign(result,calculate(exam,marks));result.marks=marks;result.status="published";await result.save();await createAuditLog({userId:req.user!.userId,action:"CORRECT",entity:"ExamResult",entityId:result._id.toString(),before:{...before,reason:d.reason},after:{marks:result.marks,obtainedMarks:result.obtainedMarks,percentage:result.percentage,grade:result.grade,result:result.result,reason:d.reason}});res.json({result});}catch(e){next(e);}}

export async function getResults(req: Request,res: Response,next: NextFunction){try{const q=req.validatedQuery as any;const filter=examFilter(req);if(q.examId)filter.examId=q.examId;if(q.studentId)filter.studentId=q.studentId;if(q.classId)filter.classId=q.classId;if(q.status)filter.status=q.status; if([UserRole.STUDENT,UserRole.PARENT].includes(req.user!.role)){const own=req.user!.profileId?.toString();if(req.user!.role===UserRole.STUDENT)filter.studentId=own;else {const children=await Student.find({schoolId:getTenantId(req),parentIds:req.user!.profileId}).select("_id").lean();filter.studentId={$in:children.map(c=>c._id)};}} const skip=(q.page-1)*q.limit;const [data,total]=await Promise.all([ExamResult.find(filter).populate("examId studentId classId sectionId marks.subjectId").sort({createdAt:-1}).skip(skip).limit(q.limit).lean(),ExamResult.countDocuments(filter)]);res.json({data,pagination:{page:q.page,limit:q.limit,total,totalPages:Math.ceil(total/q.limit)}});}catch(e){next(e);}}
export async function getResultById(req: Request,res: Response,next: NextFunction){try{const result=await ExamResult.findOne(examFilter(req,{_id:req.validatedParams.id})).populate("examId studentId classId sectionId marks.subjectId");if(!result)throw AppError.notFound("Result not found");if(req.user!.role===UserRole.STUDENT&&result.studentId._id?.toString()!==req.user!.profileId)throw AppError.forbidden("You can only view your own result");if(req.user!.role===UserRole.PARENT){const student=await Student.findOne({_id:result.studentId._id,schoolId:getTenantId(req),parentIds:req.user!.profileId}).select("_id").lean();if(!student)throw AppError.forbidden("You can only view your child's result");}res.json({result});}catch(e){next(e);}}
