import {Request,Response,NextFunction} from "express";
import {InventoryItemStatus,InventoryMovementType,InventoryMovementStatus} from "../models/InventoryItem.js";
import {InventoryItem} from "../models/InventoryItem.js";import {InventoryMovement} from "../models/InventoryMovement.js";
import {CreateInventoryItemSchema,UpdateInventoryItemSchema,InventoryItemQuerySchema,CreateInventoryMovementSchema,InventoryMovementQuerySchema,IdParamSchema} from "../validators/index.js";
import {createAuditLog} from "../services/auditLog.js";import {AppError} from "../utils/errors.js";import {escapeRegex} from "../utils/strings.js";import {getTenantId,withTenant} from "../utils/tenant.js";
const page=(p:number,l:number)=>({skip:(p-1)*l,limit:l});
export async function getItems(req:Request,res:Response,next:NextFunction){try{const q=InventoryItemQuerySchema.parse(req.query),schoolId=getTenantId(req),db:any={schoolId};if(q.status)db.status=q.status;if(q.category)db.category=q.category;if(q.search)db.$or=[{itemCode:{$regex:escapeRegex(q.search),$options:"i"}},{name:{$regex:escapeRegex(q.search),$options:"i"}}];const {skip,limit}=page(q.page,q.limit);const [data,total]=await Promise.all([InventoryItem.find(db).sort({createdAt:-1}).skip(skip).limit(limit).lean(),InventoryItem.countDocuments(db)]);res.json({data,pagination:{page:q.page,limit,total,totalPages:Math.ceil(total/limit)}})}catch(e){next(e)}}
export async function createItem(req:Request,res:Response,next:NextFunction){try{const data=withTenant(req,CreateInventoryItemSchema.parse(req.body) as any);if(await InventoryItem.exists({schoolId:data.schoolId,itemCode:data.itemCode}))throw AppError.conflict("Inventory item code already exists in this school");const item=await InventoryItem.create(data);await createAuditLog({userId:req.user!.userId,action:"CREATE",entity:"InventoryItem",entityId:item.id,after:{itemCode:item.itemCode,name:item.name}});res.status(201).json({item:item.toObject()})}catch(e){next(e)}}
export async function updateItem(req:Request,res:Response,next:NextFunction){try{const {id}=IdParamSchema.parse(req.params),data=UpdateInventoryItemSchema.parse(req.body),schoolId=getTenantId(req),item=await InventoryItem.findOne({_id:id,schoolId});if(!item)throw AppError.notFound("Inventory item not found");if(data.itemCode&&data.itemCode!==item.itemCode&&await InventoryItem.exists({schoolId,itemCode:data.itemCode,_id:{$ne:id}}))throw AppError.conflict("Inventory item code already exists in this school");if(data.status&&data.status!==InventoryItemStatus.ACTIVE&&item.quantity>0)throw AppError.conflict("Cannot retire or deactivate an item with stock remaining");if(item.status!==InventoryItemStatus.ACTIVE&&data.status!==InventoryItemStatus.ACTIVE)throw AppError.conflict("Inactive inventory item cannot be mutated");if(data.status===InventoryItemStatus.ACTIVE&&item.status!==InventoryItemStatus.ACTIVE)item.status=InventoryItemStatus.ACTIVE;if(data.itemCode!==undefined)item.itemCode=data.itemCode;if(data.name!==undefined)item.name=data.name;if(data.category!==undefined)item.category=data.category;if(data.unit!==undefined)item.unit=data.unit;if(data.reorderLevel!==undefined)item.reorderLevel=data.reorderLevel; if(data.status!==undefined)item.status=data.status;await item.save();await createAuditLog({userId:req.user!.userId,action:"UPDATE",entity:"InventoryItem",entityId:id,after:data});res.json({item:item.toObject()})}catch(e){next(e)}}
export async function deleteItem(req:Request,res:Response,next:NextFunction){try{const {id}=IdParamSchema.parse(req.params),schoolId=getTenantId(req),item=await InventoryItem.findOne({_id:id,schoolId});if(!item)throw AppError.notFound("Inventory item not found");if(item.quantity>0)throw AppError.conflict("Cannot deactivate an item with stock remaining");item.status=InventoryItemStatus.INACTIVE;await item.save();await createAuditLog({userId:req.user!.userId,action:"DELETE",entity:"InventoryItem",entityId:id,after:{status:item.status}});res.json({message:"Inventory item deactivated"})}catch(e){next(e)}}
export async function getMovements(req:Request,res:Response,next:NextFunction){try{const q=InventoryMovementQuerySchema.parse(req.query),schoolId=getTenantId(req),db:any={schoolId};if(q.itemId)db.itemId=q.itemId;if(q.type)db.type=q.type;const {skip,limit}=page(q.page,q.limit);const [data,total]=await Promise.all([InventoryMovement.find(db).populate({path:"itemId",select:"itemCode name unit"}).sort({createdAt:-1}).skip(skip).limit(limit).lean(),InventoryMovement.countDocuments(db)]);res.json({data,pagination:{page:q.page,limit,total,totalPages:Math.ceil(total/limit)}})}catch(e){next(e)}}
export async function createMovement(req:Request,res:Response,next:NextFunction){try{const data=CreateInventoryMovementSchema.parse(req.body),schoolId=getTenantId(req),delta=data.type===InventoryMovementType.STOCK_IN?data.quantity:data.type===InventoryMovementType.STOCK_OUT?-data.quantity:data.quantity;if(!await InventoryItem.exists({_id:data.itemId,schoolId,status:InventoryItemStatus.ACTIVE}))throw AppError.notFound("Active inventory item not found");const filter:any={_id:data.itemId,schoolId,status:InventoryItemStatus.ACTIVE};if(delta<0)filter.$expr={$gte:["$quantity",Math.abs(delta)]};const updated=await InventoryItem.findOneAndUpdate(filter,{$inc:{quantity:delta}},{new:false}).lean();if(!updated)throw AppError.conflict("Insufficient stock or inactive inventory item");const previous=updated.quantity,resulting=previous+delta;try{const movement=await InventoryMovement.create({schoolId,itemId:data.itemId,type:data.type,quantity:data.quantity,previousQuantity:previous,resultingQuantity:resulting,status:InventoryMovementStatus.POSTED,reason:data.reason,createdBy:req.user!.userId});await createAuditLog({userId:req.user!.userId,action:"CREATE",entity:"InventoryMovement",entityId:movement.id,after:{itemId:data.itemId,type:data.type,quantity:data.quantity,resultingQuantity:resulting}});res.status(201).json({movement:movement.toObject()})}catch(e){await InventoryItem.updateOne({_id:data.itemId,schoolId,quantity:resulting},{$inc:{quantity:-delta}});throw e}}catch(e){next(e)}}
