import {config} from "dotenv";import {resolve} from "node:path";import {test,expect} from "@playwright/test";config({path:resolve(process.cwd(),".env")});const baseUrl=process.env.E2E_API_URL;const password=process.env.E2E_FIXTURE_PASSWORD;const api=(p:string)=>{expect(baseUrl).toBeTruthy();return new URL(p,baseUrl).toString()};
async function login(playwright:any,email:string,schoolCode="SCH-E2E-A"){const ctx=await playwright.request.newContext();try{const r=await ctx.post(api("/api/v1/auth/login"),{data:{email,password,schoolCode}});const b=await r.json().catch(()=>({}));expect(r.status(),JSON.stringify(b)).toBe(200);return b.accessToken??b.data?.accessToken}finally{await ctx.dispose()}}
async function body(r:any){return r.json().catch(()=>({}))}
test("transport enforces tenant isolation, RBAC, lifecycle and capacity concurrency",async({request,playwright})=>{const principal=await login(playwright,"principal.e2e.a@example.com");const h={Authorization:`Bearer ${principal}`};const b=await request.get(api("/api/v1/students?status=active&page=1&limit=2"),{headers:h});const students=(await body(b)).data;expect(b.status()).toBe(200);expect(students.length).toBeGreaterThanOrEqual(2);const s1=students[0]._id,s2=students[1]._id;const suffix=`ALO33-${Date.now()}`;
const rr=await request.post(api("/api/v1/transport/routes"),{headers:h,data:{name:`Route ${suffix}`,code:suffix}});const rb=await body(rr);expect(rr.status(),JSON.stringify(rb)).toBe(201);const routeId=rb.route._id;const sr=await request.post(api(`/api/v1/transport/routes/${routeId}/stops`),{headers:h,data:{name:"Main Gate",sequence:1}});const sb=await body(sr);expect(sr.status(),JSON.stringify(sb)).toBe(201);const stopId=sb.stop._id;const vr=await request.post(api("/api/v1/transport/vehicles"),{headers:h,data:{registrationNo:`${suffix}-BUS`,vehicleType:"bus",capacity:1}});const vb=await body(vr);expect(vr.status(),JSON.stringify(vb)).toBe(201);const vehicleId=vb.vehicle._id;
const accountant=await login(playwright,"accountant.e2e.a@example.com");const ah={Authorization:`Bearer ${accountant}`};expect((await request.get(api("/api/v1/transport/routes"),{headers:ah})).status()).toBe(200);expect((await request.post(api("/api/v1/transport/routes"),{headers:ah,data:{name:"Denied",code:`DENY-${suffix}`}})).status()).toBe(403);
const principalB=await login(playwright,"principal.e2e.b@example.com","SCH-E2E-B");const cross=await request.put(api(`/api/v1/transport/routes/${routeId}`),{headers:{Authorization:`Bearer ${principalB}`},data:{name:"Cross Tenant"}});expect(cross.status()).toBe(404);
const [a1,a2]=await Promise.all([request.post(api("/api/v1/transport/allocations"),{headers:h,data:{studentId:s1,routeId,vehicleId,stopId}}),request.post(api("/api/v1/transport/allocations"),{headers:h,data:{studentId:s2,routeId,vehicleId,stopId}})]);const statuses=[a1.status(),a2.status()].sort((a,b)=>a-b);expect(statuses).toEqual([201,409]);const winner=await body(a1.status()===201?a1:a2);const winnerStudent=a1.status()===201?s1:s2;
const vehicleAfterRace=await request.get(api(`/api/v1/transport/vehicles?search=${encodeURIComponent(`${suffix}-BUS`)}&page=1&limit=10`),{headers:h});expect((await body(vehicleAfterRace)).data[0].allocatedSeats).toBe(1);const duplicate=await request.post(api("/api/v1/transport/allocations"),{headers:h,data:{studentId:winnerStudent,routeId,vehicleId,stopId}});expect(duplicate.status()).toBe(409);const vehicleAfterRollback=await request.get(api(`/api/v1/transport/vehicles?search=${encodeURIComponent(`${suffix}-BUS`)}&page=1&limit=10`),{headers:h});expect((await body(vehicleAfterRollback)).data[0].allocatedSeats).toBe(1);
const del=await request.delete(api(`/api/v1/transport/allocations/${winner.allocation._id}`),{headers:h});expect(del.status()).toBe(200);const vehicleAfterDelete=await request.get(api(`/api/v1/transport/vehicles?search=${encodeURIComponent(`${suffix}-BUS`)}&page=1&limit=10`),{headers:h});expect((await body(vehicleAfterDelete)).data[0].allocatedSeats).toBe(0);const bad=await request.post(api("/api/v1/transport/allocations"),{headers:h,data:{studentId:s1,routeId,vehicleId:"67e000000000000000000002",stopId}});expect([404,409]).toContain(bad.status())});
