import {config} from "dotenv";import {resolve} from "node:path";import {test,expect} from "@playwright/test";config({path:resolve(process.cwd(),".env")});
const baseUrl=process.env.E2E_API_URL;const password=process.env.E2E_FIXTURE_PASSWORD;const api=(p:string)=>{expect(baseUrl).toBeTruthy();return new URL(p,baseUrl).toString()};
async function login(playwright:any,email:string,schoolCode="SCH-E2E-A"){const ctx=await playwright.request.newContext();try{const r=await ctx.post(api("/api/v1/auth/login"),{data:{email,password,schoolCode}});const b=await r.json().catch(()=>({}));expect(r.status(),JSON.stringify(b)).toBe(200);return b.accessToken??b.data?.accessToken}finally{await ctx.dispose()}}
async function body(r:any){return r.json().catch(()=>({}))}
test("inventory enforces tenant isolation, RBAC, lifecycle and concurrent non-negative stock",async({request,playwright})=>{const principal=await login(playwright,"principal.e2e.a@example.com");const h={Authorization:`Bearer ${principal}`};const suffix=`ALO34-${Date.now()}`;const create=await request.post(api("/api/v1/inventory/items"),{headers:h,data:{itemCode:suffix,name:"Printer Paper",category:"Stationery",unit:"ream",reorderLevel:1}});const cb=await body(create);expect(create.status(),JSON.stringify(cb)).toBe(201);const itemId=cb.item._id;
const accountant=await login(playwright,"accountant.e2e.a@example.com");const ah={Authorization:`Bearer ${accountant}`};expect((await request.get(api("/api/v1/inventory/items"),{headers:ah})).status()).toBe(200);expect((await request.post(api("/api/v1/inventory/items"),{headers:ah,data:{itemCode:`DENY-${suffix}`,name:"Denied",unit:"piece"}})).status()).toBe(403);
const principalB=await login(playwright,"principal.e2e.b@example.com","SCH-E2E-B");expect((await request.get(api(`/api/v1/inventory/items?search=${suffix}`),{headers:{Authorization:`Bearer ${principalB}`}})).status()).toBe(200);expect((await body(await request.get(api(`/api/v1/inventory/items?search=${suffix}`),{headers:{Authorization:`Bearer ${principalB}`}}))).data).toHaveLength(0);
const stockIn=await request.post(api("/api/v1/inventory/movements"),{headers:h,data:{itemId,type:"stock_in",quantity:1,reason:"Opening stock"}});expect(stockIn.status()).toBe(201);
const [m1,m2]=await Promise.all([request.post(api("/api/v1/inventory/movements"),{headers:h,data:{itemId,type:"stock_out",quantity:1}}),request.post(api("/api/v1/inventory/movements"),{headers:h,data:{itemId,type:"stock_out",quantity:1}})]);expect([m1.status(),m2.status()].sort((a,b)=>a-b)).toEqual([200-1,409]);
const list=await request.get(api(`/api/v1/inventory/items?search=${suffix}`),{headers:h});const item=(await body(list)).data[0];expect(item.quantity).toBe(0);
const deniedUpdate=await request.put(api(`/api/v1/inventory/items/${itemId}`),{headers:h,data:{status:"retired"}});expect(deniedUpdate.status()).toBe(200);expect((await body(deniedUpdate)).item.status).toBe("retired");const rejected=await request.post(api("/api/v1/inventory/movements"),{headers:h,data:{itemId,type:"stock_in",quantity:1}});expect(rejected.status()).toBe(404);});
