import { config } from "dotenv";
import { resolve } from "node:path";
import { test, expect, request as playwrightRequest } from "@playwright/test";
config({ path: resolve(process.cwd(), ".env") });
const apiUrl = process.env.E2E_API_URL; const fixturePassword = process.env.E2E_FIXTURE_PASSWORD; const schoolCode = process.env.E2E_SCHOOL_A_CODE || "SCH-PHASE1-A"; const studentId = process.env.E2E_SCHOOL_A_STUDENT_ID;
const principalEmail = "principal.a@phase1.example.com"; const studentEmail = "student.a@phase1.example.com";
async function login(api: any, email: string) { const response = await api.post("/api/v1/auth/login", { data: { email, password: fixturePassword, schoolCode } }); const body = await response.json(); expect(response.status(), JSON.stringify(body)).toBe(200); return body.accessToken ?? body.data?.accessToken; }
function auth(token: string) { return { headers: { Authorization: `Bearer ${token}` } }; }
async function create(api: any, token: string, data: any) { const response = await api.post("/api/v1/timetable", { data, ...auth(token) }); const body = await response.json().catch(() => ({})); return { response, body }; }
async function ensureSubject(api: any, token: string, classId: string, prefix: string) { const response = await api.get(`/api/v1/academics/subjects?classId=${classId}`, auth(token)); const body = await response.json(); const existing = (body.data || []).find((item: any) => (item.classIds || []).some((id: any) => (id?._id || id) === classId)); if (existing) return { id: existing._id, created: false }; const createResponse = await api.post("/api/v1/academics/subjects", { data: { name: `Phase 6 ${prefix} Subject`, code: `P6${Date.now().toString().slice(-6)}${prefix.slice(0, 1)}`, classIds: [classId] }, ...auth(token) }); const createBody = await createResponse.json(); expect(createResponse.status(), JSON.stringify(createBody)).toBe(201); const subject = createBody.subject ?? createBody.data?.subject ?? createBody.data; return { id: subject._id, created: true }; }
async function ensureTeacher(api: any, token: string, teachers: any[]) { if (teachers.length > 1) return { teacher: teachers[1], created: false }; const suffix = Date.now().toString().slice(-8); const response = await api.post("/api/v1/teachers", { data: { employeeId: `P6${suffix}`, firstName: "Phase6", lastName: "Fixture", email: `phase6-${suffix}@example.com`, phone: "9999999999", qualification: "Test", experience: 0, joiningDate: "2026-01-01T00:00:00.000Z", salary: 0, subjects: [], classTeacherOf: [], status: "active" }, ...auth(token) }); const body = await response.json(); expect(response.status(), JSON.stringify(body)).toBe(201); return { teacher: body.teacher ?? body.data?.teacher ?? body.data, created: true }; }

test.beforeAll(() => { expect(apiUrl).toBeTruthy(); expect(fixturePassword).toBeTruthy(); expect(studentId).toBeTruthy(); });

test.describe("Phase 6 Timetable API", () => {
  test("rejects class, teacher and room conflicts", async () => {
    const api = await playwrightRequest.newContext({ baseURL: apiUrl }); const token = await login(api, principalEmail);
    const studentResponse = await api.get(`/api/v1/students/${studentId}`, auth(token)); const studentBody = await studentResponse.json(); const student = studentBody.student ?? studentBody.data?.student ?? studentBody.data ?? studentBody; const classId = student.classId?._id || student.classId; const sectionId = student.sectionId?._id || student.sectionId; const schoolId = student.classId?.schoolId?._id || student.classId?.schoolId;
    const years = (await (await api.get("/api/v1/academic-years", auth(token))).json()).data || []; const academicYearId = years.find((year: any) => year.isCurrent)?._id || years[0]?._id;
    const teachers = (await (await api.get("/api/v1/teachers?limit=100&status=active", auth(token))).json()).data || []; const classes = (await (await api.get("/api/v1/academics/classes?limit=100", auth(token))).json()).data || [];
    expect(classId).toMatch(/^[a-f\d]{24}$/i); expect(academicYearId).toMatch(/^[a-f\d]{24}$/i); expect(teachers.length).toBeGreaterThan(0);
    const extraTeacher = await ensureTeacher(api, token, teachers); const subject = await ensureSubject(api, token, classId, "A"); const otherClass = classes.find((item: any) => item._id !== classId); const otherSubject = otherClass ? await ensureSubject(api, token, otherClass._id, "B") : null;
    const base = { academicYearId, classId, sectionId: sectionId || undefined, subjectId: subject.id, teacherId: teachers[0]._id, dayOfWeek: 1, startTime: "10:00", endTime: "10:45", roomNumber: "QA-101", periodLabel: "P1" };
    const created = await create(api, token, base); expect(created.response.status(), JSON.stringify(created.body)).toBe(201); const createdId = created.body.timetable?._id || created.body.data?._id; expect(createdId).toMatch(/^[a-f\d]{24}$/i);
    const classConflict = await create(api, token, { ...base, teacherId: extraTeacher.teacher._id, startTime: "10:15", endTime: "11:00" }); expect(classConflict.response.status(), JSON.stringify(classConflict.body)).toBe(409); expect(classConflict.body.code).toBe("TIMETABLE_CLASS_CONFLICT");
    if (otherClass && otherSubject) { const teacherConflict = await create(api, token, { ...base, classId: otherClass._id, sectionId: undefined, subjectId: otherSubject.id, startTime: "10:15", endTime: "11:00" }); expect(teacherConflict.response.status(), JSON.stringify(teacherConflict.body)).toBe(409); expect(teacherConflict.body.code).toBe("TIMETABLE_TEACHER_CONFLICT"); const roomConflict = await create(api, token, { ...base, classId: otherClass._id, sectionId: undefined, subjectId: otherSubject.id, teacherId: extraTeacher.teacher._id, startTime: "10:15", endTime: "11:00" }); expect(roomConflict.response.status(), JSON.stringify(roomConflict.body)).toBe(409); expect(roomConflict.body.code).toBe("TIMETABLE_ROOM_CONFLICT"); }
    await api.delete(`/api/v1/timetable/${createdId}`, auth(token)); if (subject.created) await api.delete(`/api/v1/academics/subjects/${subject.id}`, auth(token)); if (otherSubject?.created) await api.delete(`/api/v1/academics/subjects/${otherSubject.id}`, auth(token)); if (extraTeacher.created) await api.delete(`/api/v1/teachers/${extraTeacher.teacher._id}`, auth(token)); await api.dispose();
  });

  test("student sees only their class timetable and cannot write", async () => {
    const principalApi = await playwrightRequest.newContext({ baseURL: apiUrl }); const studentApi = await playwrightRequest.newContext({ baseURL: apiUrl }); const principalToken = await login(principalApi, principalEmail); const studentToken = await login(studentApi, studentEmail);
    const studentResponse = await principalApi.get(`/api/v1/students/${studentId}`, auth(principalToken)); const studentBody = await studentResponse.json(); const student = studentBody.student ?? studentBody.data?.student ?? studentBody.data ?? studentBody; const classId = student.classId?._id || student.classId;
    const response = await studentApi.get("/api/v1/timetable?limit=100", auth(studentToken)); expect(response.status()).toBe(200); const entries = (await response.json()).data || []; expect(entries.every((entry: any) => (entry.classId?._id || entry.classId) === classId)).toBe(true);
    const denied = await studentApi.post("/api/v1/timetable", { data: { classId, academicYearId: classId, subjectId: classId, teacherId: classId, dayOfWeek: 1, startTime: "12:00", endTime: "12:45" }, ...auth(studentToken) }); expect(denied.status()).toBe(403); await principalApi.dispose(); await studentApi.dispose();
  });
});
