import { useCallback, useEffect, useMemo, useState } from "react";
import { Pressable, RefreshControl, ScrollView, StyleSheet, Text, TextInput, View } from "react-native";
import { ApiError } from "../auth/api";
import { EmptyState, ErrorState, LoadingState } from "../ui/StateView";
import { mobileTheme } from "../ui/theme";

type Request = <T>(path: string, options?: RequestInit) => Promise<T>;
type OptionData = { academicYear: { _id: string; name: string }; classes: Array<Record<string, unknown>>; sections: Array<Record<string, unknown>>; subjects: Array<Record<string, unknown>> };
type Homework = { _id: string; title: string; description?: string; classId?: Record<string, unknown>; sectionId?: Record<string, unknown>; subjectId?: Record<string, unknown>; assignedDate: string; dueDate: string };
const idOf = (item: unknown) => typeof item === "string" ? item : item && typeof item === "object" ? String((item as Record<string, unknown>)._id ?? "") : "";
const labelOf = (item: unknown, key: string, fallback = "—") => { if (!item || typeof item !== "object") return fallback; const raw = (item as Record<string, unknown>)[key]; return typeof raw === "string" || typeof raw === "number" ? String(raw) : fallback; };
const today = () => new Date().toISOString().slice(0, 10);

function Choice({ label, selected, onPress, disabled = false }: { label: string; selected: boolean; onPress: () => void; disabled?: boolean }) {
  return <Pressable accessibilityRole="button" accessibilityLabel={label} accessibilityState={{ selected, disabled }} disabled={disabled} onPress={onPress} style={({ pressed }) => [styles.choice, selected && styles.choiceSelected, disabled && styles.disabled, pressed && styles.pressed]}><Text style={[styles.choiceText, selected && styles.choiceTextSelected]}>{label}</Text></Pressable>;
}

export function TeacherHomeworkScreen({ request }: { request: Request }) {
  const [options, setOptions] = useState<OptionData | null>(null); const [items, setItems] = useState<Homework[]>([]); const [error, setError] = useState<string | null>(null); const [refreshing, setRefreshing] = useState(false); const [saving, setSaving] = useState(false); const [message, setMessage] = useState<string | null>(null);
  const [classId, setClassId] = useState(""); const [sectionId, setSectionId] = useState(""); const [subjectId, setSubjectId] = useState(""); const [title, setTitle] = useState(""); const [description, setDescription] = useState(""); const [assignedDate, setAssignedDate] = useState(today()); const [dueDate, setDueDate] = useState(today());
  const load = useCallback(async () => { setRefreshing(true); setError(null); try { const next = await request<OptionData>("/portal/teacher/homework/options"); setOptions(next); const classes = next.classes ?? []; const firstClass = idOf(classes[0]); setClassId((current) => current || firstClass); const firstSection = (next.sections ?? []).find((item) => idOf(item.classId) === (classId || firstClass)); setSectionId((current) => current || idOf(firstSection)); const firstSubject = (next.subjects ?? []).find((item) => (item.classIds as unknown[] | undefined)?.map(String).includes(classId || firstClass)); setSubjectId((current) => current || idOf(firstSubject)); } catch (cause) { setError(cause instanceof ApiError ? cause.message : "Unable to load homework workspace."); } finally { setRefreshing(false); } }, [request, classId]);
  const loadItems = useCallback(async () => { try { const params = new URLSearchParams({ limit: "50" }); if (classId) params.set("classId", classId); if (sectionId) params.set("sectionId", sectionId); if (subjectId) params.set("subjectId", subjectId); const result = await request<{ data: Homework[] }>(`/portal/teacher/homework?${params.toString()}`); setItems(result.data ?? []); } catch (cause) { setError(cause instanceof ApiError ? cause.message : "Unable to load homework."); } }, [request, classId, sectionId, subjectId]);
  useEffect(() => { void load(); }, [load]); useEffect(() => { if (options) void loadItems(); }, [options, loadItems]);
  const sections = useMemo(() => (options?.sections ?? []).filter((item) => idOf(item.classId) === classId), [options, classId]); const subjects = useMemo(() => (options?.subjects ?? []).filter((item) => (item.classIds as unknown[] | undefined)?.map(String).includes(classId)), [options, classId]);
  const create = async () => { if (!options || !title.trim() || !classId || !subjectId || !assignedDate || !dueDate || dueDate < assignedDate) return; setSaving(true); setError(null); setMessage(null); try { await request("/portal/teacher/homework", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ title: title.trim(), description: description.trim() || undefined, classId, sectionId: sectionId || undefined, subjectId, academicYearId: options.academicYear._id, assignedDate, dueDate }) }); setTitle(""); setDescription(""); setAssignedDate(today()); setDueDate(today()); setMessage("Homework assigned successfully."); await loadItems(); } catch (cause) { setError(cause instanceof ApiError ? cause.message : "Unable to assign homework."); } finally { setSaving(false); } };
  if (!options && !error) return <LoadingState message="Loading homework workspace…" />;
  if (!options && error) return <View style={styles.center}><ErrorState message={error} onRetry={() => void load()} /></View>;
  if (!options) return null;
  return <ScrollView contentContainerStyle={styles.container} refreshControl={<RefreshControl refreshing={refreshing} onRefresh={() => { void load(); void loadItems(); }} accessibilityLabel="Refresh homework workspace" />}>
    <Text style={styles.eyebrow}>TEACHER WORKSPACE</Text><Text accessibilityRole="header" style={styles.title}>Homework</Text><Text style={styles.subtitle}>Assign work only to classes and subjects returned by your teaching assignment.</Text>
    {error ? <ErrorState message={error} onRetry={() => void loadItems()} /> : null}{message ? <Text accessibilityLiveRegion="polite" style={styles.success}>{message}</Text> : null}
    <View style={styles.card}><Text accessibilityRole="header" style={styles.sectionTitle}>Assignment scope</Text><Text style={styles.label}>Class</Text><View style={styles.wrap}>{options.classes.map((item) => <Choice key={idOf(item)} label={labelOf(item, "displayName", labelOf(item, "name", "Class"))} selected={idOf(item) === classId} onPress={() => { setClassId(idOf(item)); setSectionId(""); setSubjectId(""); }} />)}</View>
      <Text style={styles.label}>Section</Text><View style={styles.wrap}><Choice label="All sections" selected={!sectionId} onPress={() => setSectionId("")} />{sections.map((item) => <Choice key={idOf(item)} label={labelOf(item, "name", "Section")} selected={idOf(item) === sectionId} onPress={() => setSectionId(idOf(item))} />)}</View>
      <Text style={styles.label}>Subject</Text><View style={styles.wrap}>{subjects.map((item) => <Choice key={idOf(item)} label={labelOf(item, "name", "Subject")} selected={idOf(item) === subjectId} onPress={() => setSubjectId(idOf(item))} />)}</View>
    </View>
    <View style={styles.card}><Text accessibilityRole="header" style={styles.sectionTitle}>Assign homework</Text><TextInput accessibilityLabel="Homework title" placeholder="Title" value={title} onChangeText={setTitle} style={styles.input} /><TextInput accessibilityLabel="Homework description" placeholder="Instructions (optional)" value={description} onChangeText={setDescription} multiline style={[styles.input, styles.multiline]} /><TextInput accessibilityLabel="Assigned date" placeholder="Assigned date YYYY-MM-DD" value={assignedDate} onChangeText={setAssignedDate} style={styles.input} /><TextInput accessibilityLabel="Due date" placeholder="Due date YYYY-MM-DD" value={dueDate} onChangeText={setDueDate} style={styles.input} /><Pressable accessibilityRole="button" accessibilityLabel={saving ? "Assigning homework" : "Assign homework"} accessibilityState={{ disabled: saving || !title.trim() || !classId || !subjectId || dueDate < assignedDate, busy: saving }} disabled={saving || !title.trim() || !classId || !subjectId || dueDate < assignedDate} onPress={() => void create()} style={({ pressed }) => [styles.save, (saving || pressed) && styles.pressed]}><Text style={styles.saveText}>{saving ? "Assigning…" : "Assign homework"}</Text></Pressable></View>
    <View style={styles.card}><Text accessibilityRole="header" style={styles.sectionTitle}>Assigned homework</Text>{items.length ? items.map((item) => <View key={item._id} style={styles.row}><Text style={styles.rowTitle}>{item.title}</Text>{item.description ? <Text style={styles.rowBody}>{item.description}</Text> : null}<Text style={styles.rowMeta}>{labelOf(item.classId, "displayName", "Class")} · {labelOf(item.sectionId, "name", "All sections")} · {labelOf(item.subjectId, "name", "Subject")}</Text><Text style={styles.rowMeta}>Assigned {item.assignedDate} · Due {item.dueDate}</Text></View>) : <EmptyState message="No homework in this view." />}</View>
  </ScrollView>;
}
const styles = StyleSheet.create({ container: { padding: mobileTheme.spacing.xl, paddingBottom: 40, backgroundColor: mobileTheme.colors.background }, center: { flex: 1, justifyContent: "center", padding: mobileTheme.spacing.xxl }, eyebrow: { fontSize: mobileTheme.typography.small, fontWeight: "700", letterSpacing: 1.4, color: mobileTheme.colors.textMuted }, title: { fontSize: mobileTheme.typography.title, fontWeight: "700", marginTop: 6, color: mobileTheme.colors.text }, subtitle: { marginTop: 6, color: mobileTheme.colors.textMuted, lineHeight: 21 }, success: { marginTop: 10, fontWeight: "600", color: mobileTheme.colors.text }, card: { marginTop: mobileTheme.spacing.lg, padding: mobileTheme.spacing.lg, backgroundColor: mobileTheme.colors.surface, borderRadius: mobileTheme.radius.md, borderWidth: 1, borderColor: mobileTheme.colors.border }, sectionTitle: { fontSize: mobileTheme.typography.section, fontWeight: "700", color: mobileTheme.colors.text, marginBottom: 10 }, label: { fontWeight: "700", color: mobileTheme.colors.text, marginTop: 8, marginBottom: 6 }, wrap: { flexDirection: "row", flexWrap: "wrap", gap: 8 }, choice: { minHeight: mobileTheme.touchTarget, minWidth: 74, paddingHorizontal: 12, justifyContent: "center", alignItems: "center", borderWidth: 1, borderColor: mobileTheme.colors.border, borderRadius: mobileTheme.radius.sm }, choiceSelected: { backgroundColor: mobileTheme.colors.active, borderColor: mobileTheme.colors.active }, choiceText: { color: mobileTheme.colors.text, fontWeight: "600" }, choiceTextSelected: { color: mobileTheme.colors.activeText }, disabled: { opacity: 0.5 }, pressed: { opacity: 0.72 }, input: { minHeight: mobileTheme.touchTarget, borderWidth: 1, borderColor: mobileTheme.colors.border, borderRadius: mobileTheme.radius.sm, paddingHorizontal: 12, marginBottom: 10, backgroundColor: mobileTheme.colors.surface, color: mobileTheme.colors.text }, multiline: { minHeight: 90, paddingTop: 12, textAlignVertical: "top" }, save: { minHeight: mobileTheme.touchTarget, justifyContent: "center", alignItems: "center", borderRadius: mobileTheme.radius.sm, backgroundColor: mobileTheme.colors.text, marginTop: 4 }, saveText: { color: mobileTheme.colors.surface, fontWeight: "700", fontSize: 16 }, row: { paddingVertical: 12, borderTopWidth: 1, borderTopColor: mobileTheme.colors.borderSubtle }, rowTitle: { fontWeight: "700", color: mobileTheme.colors.text, fontSize: 16 }, rowBody: { marginTop: 4, color: mobileTheme.colors.textMuted }, rowMeta: { marginTop: 5, color: mobileTheme.colors.textSubtle, fontSize: mobileTheme.typography.small } });