import { useCallback, useEffect, useMemo, useState } from "react";
import { Pressable, RefreshControl, ScrollView, StyleSheet, Text, TextInput, View } from "react-native";
import { ApiError } from "../auth/api";
import { EmptyState, ErrorState, LoadingState } from "../ui/StateView";
import { mobileTheme } from "../ui/theme";

type Request = <T>(path: string, options?: RequestInit) => Promise<T>;
type Exam = { _id: string; name: string; examType: string; classId: Record<string, unknown>; startDate: string; endDate: string; status: "draft" | "published"; subjects: Array<{ subjectId: Record<string, unknown>; maxMarks: number; passMarks: number }> };
type Workspace = { assignedClasses: Array<Record<string, unknown>>; assignedStudents: Array<Record<string, unknown>> };
const idOf = (item: unknown) => typeof item === "string" ? item : item && typeof item === "object" ? String((item as Record<string, unknown>)._id ?? "") : "";
const nameOf = (item: unknown, fallback = "—") => item && typeof item === "object" ? String((item as Record<string, unknown>).name ?? (item as Record<string, unknown>).displayName ?? fallback) : fallback;

export function TeacherMarksScreen({ request }: { request: Request }) {
  const [workspace, setWorkspace] = useState<Workspace | null>(null); const [exams, setExams] = useState<Exam[]>([]); const [classId, setClassId] = useState(""); const [examId, setExamId] = useState(""); const [studentId, setStudentId] = useState(""); const [marks, setMarks] = useState<Record<string, string>>({}); const [error, setError] = useState<string | null>(null); const [message, setMessage] = useState<string | null>(null); const [saving, setSaving] = useState(false); const [refreshing, setRefreshing] = useState(false);
  const load = useCallback(async () => { setRefreshing(true); setError(null); try { const next = await request<Workspace>("/portal/teacher/workspace"); setWorkspace(next); const firstClass = idOf(next.assignedClasses[0]); setClassId((current) => current || firstClass); const firstStudent = next.assignedStudents.find((item) => idOf(item.classId) === (classId || firstClass)); setStudentId((current) => current || idOf(firstStudent)); } catch (cause) { setError(cause instanceof ApiError ? cause.message : "Unable to load marks workspace."); } finally { setRefreshing(false); } }, [request, classId]);
  const loadExams = useCallback(async () => { if (!classId) return; try { const result = await request<{ data: Exam[] }>(`/portal/teacher/marks?classId=${encodeURIComponent(classId)}`); setExams(result.data ?? []); setExamId((current) => current && (result.data ?? []).some((exam) => exam._id === current) ? current : (result.data?.[0]?._id ?? "")); } catch (cause) { setError(cause instanceof ApiError ? cause.message : "Unable to load assigned exams."); } }, [request, classId]);
  useEffect(() => { void load(); }, [load]); useEffect(() => { void loadExams(); }, [loadExams]);
  const students = useMemo(() => (workspace?.assignedStudents ?? []).filter((item) => idOf(item.classId) === classId), [workspace, classId]); const exam = exams.find((item) => item._id === examId); const subjects = exam?.subjects ?? [];
  useEffect(() => { if (!students.some((item) => idOf(item) === studentId)) setStudentId(idOf(students[0])); }, [students, studentId]); useEffect(() => { const next: Record<string, string> = {}; subjects.forEach((item) => { next[idOf(item.subjectId)] = ""; }); setMarks(next); }, [examId]);
  const save = async () => { if (!exam || !studentId || exam.status === "published" || subjects.some((item) => marks[idOf(item.subjectId)] === "")) return; const payload = subjects.map((item) => ({ subjectId: idOf(item.subjectId), value: Number(marks[idOf(item.subjectId)]), absent: false })); if (payload.some((item, index) => !Number.isFinite(item.value) || item.value < 0 || item.value > subjects[index].maxMarks)) { setError("Enter valid marks within each subject maximum."); return; } setSaving(true); setError(null); setMessage(null); try { await request(`/exams/${exam._id}/results`, { method: "PUT", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ studentId, marks: payload }) }); setMessage("Marks saved successfully."); } catch (cause) { setError(cause instanceof ApiError ? cause.message : "Unable to save marks."); } finally { setSaving(false); } };
  if (!workspace && !error) return <LoadingState message="Loading marks workspace…" />; if (!workspace && error) return <View style={styles.center}><ErrorState message={error} onRetry={() => void load()} /></View>; if (!workspace) return null;
  return <ScrollView contentContainerStyle={styles.container} refreshControl={<RefreshControl refreshing={refreshing} onRefresh={() => { void load(); void loadExams(); }} accessibilityLabel="Refresh marks workspace" />}>
    <Text style={styles.eyebrow}>TEACHER WORKSPACE</Text><Text accessibilityRole="header" style={styles.title}>Marks</Text><Text style={styles.subtitle}>Enter marks only for exams and students within your server-authorized teaching scope.</Text>
    {error ? <ErrorState message={error} onRetry={() => void loadExams()} /> : null}{message ? <Text accessibilityLiveRegion="polite" style={styles.success}>{message}</Text> : null}
    <View style={styles.card}><Text accessibilityRole="header" style={styles.sectionTitle}>Class</Text><View style={styles.wrap}>{workspace.assignedClasses.map((item) => <Choice key={idOf(item)} label={nameOf(item, "Class")} selected={idOf(item) === classId} onPress={() => { setClassId(idOf(item)); setExamId(""); setMessage(null); }} />)}</View><Text style={styles.label}>Exam</Text>{exams.length ? <View style={styles.wrap}>{exams.map((item) => <Choice key={item._id} label={`${item.name} · ${item.status}`} selected={item._id === examId} onPress={() => setExamId(item._id)} />)}</View> : <EmptyState message="No exams are available for your assigned classes or subjects." />}<Text style={styles.label}>Student</Text>{students.length ? <View style={styles.wrap}>{students.map((item) => <Choice key={idOf(item)} label={`${nameOf(item, "Student")} ${String((item as Record<string, unknown>).admissionNo ?? "")}`} selected={idOf(item) === studentId} onPress={() => setStudentId(idOf(item))} />)}</View> : <EmptyState message="No active students are assigned to this class." />}</View>
    {exam ? <View style={styles.card}><Text accessibilityRole="header" style={styles.sectionTitle}>{exam.name}</Text><Text style={styles.meta}>{exam.startDate} to {exam.endDate} · {exam.status === "published" ? "Published — marks are locked" : "Draft — marks can be entered"}</Text>{subjects.map((item) => <View key={idOf(item.subjectId)} style={styles.markRow}><View style={styles.markInfo}><Text style={styles.subject}>{nameOf(item.subjectId, "Subject")}</Text><Text style={styles.meta}>Max {item.maxMarks} · Pass {item.passMarks}</Text></View><TextInput accessibilityLabel={`Marks for ${nameOf(item.subjectId, "subject")}`} editable={exam.status !== "published"} keyboardType="decimal-pad" placeholder="0" value={marks[idOf(item.subjectId)] ?? ""} onChangeText={(text) => setMarks((current) => ({ ...current, [idOf(item.subjectId)]: text.replace(/[^0-9.]/g, "") }))} style={styles.markInput} /></View>)}<Pressable accessibilityRole="button" accessibilityLabel={saving ? "Saving marks" : "Save marks"} accessibilityState={{ disabled: saving || exam.status === "published" || !studentId || subjects.some((item) => marks[idOf(item.subjectId)] === ""), busy: saving }} disabled={saving || exam.status === "published" || !studentId || subjects.some((item) => marks[idOf(item.subjectId)] === "")} onPress={() => void save()} style={({ pressed }) => [styles.save, (saving || pressed) && styles.pressed, exam.status === "published" && styles.disabled]}><Text style={styles.saveText}>{saving ? "Saving…" : exam.status === "published" ? "Published — locked" : "Save marks"}</Text></Pressable></View> : null}
  </ScrollView>;
}
function Choice({ label, selected, onPress }: { label: string; selected: boolean; onPress: () => void }) { return <Pressable accessibilityRole="button" accessibilityLabel={label} accessibilityState={{ selected }} onPress={onPress} style={({ pressed }) => [styles.choice, selected && styles.choiceSelected, pressed && styles.pressed]}><Text style={[styles.choiceText, selected && styles.choiceTextSelected]}>{label}</Text></Pressable>; }
const styles = StyleSheet.create({ container: { padding: mobileTheme.spacing.xl, paddingBottom: 40, backgroundColor: mobileTheme.colors.background }, center: { flex: 1, justifyContent: "center", padding: mobileTheme.spacing.xxl }, eyebrow: { fontSize: mobileTheme.typography.small, fontWeight: "700", letterSpacing: 1.4, color: mobileTheme.colors.textMuted }, title: { fontSize: mobileTheme.typography.title, fontWeight: "700", marginTop: 6, color: mobileTheme.colors.text }, subtitle: { marginTop: 6, color: mobileTheme.colors.textMuted, lineHeight: 21 }, success: { marginTop: 10, fontWeight: "600", color: mobileTheme.colors.text }, card: { marginTop: mobileTheme.spacing.lg, padding: mobileTheme.spacing.lg, backgroundColor: mobileTheme.colors.surface, borderRadius: mobileTheme.radius.md, borderWidth: 1, borderColor: mobileTheme.colors.border }, sectionTitle: { fontSize: mobileTheme.typography.section, fontWeight: "700", color: mobileTheme.colors.text, marginBottom: 10 }, label: { fontWeight: "700", color: mobileTheme.colors.text, marginTop: 14, marginBottom: 6 }, wrap: { flexDirection: "row", flexWrap: "wrap", gap: 8 }, choice: { minHeight: mobileTheme.touchTarget, minWidth: 74, paddingHorizontal: 12, justifyContent: "center", alignItems: "center", borderWidth: 1, borderColor: mobileTheme.colors.border, borderRadius: mobileTheme.radius.sm }, choiceSelected: { backgroundColor: mobileTheme.colors.active, borderColor: mobileTheme.colors.active }, choiceText: { color: mobileTheme.colors.text, fontWeight: "600" }, choiceTextSelected: { color: mobileTheme.colors.activeText }, markRow: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", paddingVertical: 12, borderTopWidth: 1, borderTopColor: mobileTheme.colors.borderSubtle }, markInfo: { flex: 1, paddingRight: 12 }, subject: { fontWeight: "700", color: mobileTheme.colors.text }, meta: { color: mobileTheme.colors.textMuted, marginTop: 3, fontSize: mobileTheme.typography.small }, markInput: { width: 90, minHeight: mobileTheme.touchTarget, borderWidth: 1, borderColor: mobileTheme.colors.border, borderRadius: mobileTheme.radius.sm, paddingHorizontal: 12, textAlign: "center", color: mobileTheme.colors.text }, save: { minHeight: mobileTheme.touchTarget, justifyContent: "center", alignItems: "center", borderRadius: mobileTheme.radius.sm, backgroundColor: mobileTheme.colors.text, marginTop: 16 }, saveText: { color: mobileTheme.colors.surface, fontWeight: "700", fontSize: 16 }, disabled: { opacity: 0.5 }, pressed: { opacity: 0.72 } });