import { useState } from "react";
import { DndContext, PointerSensor, closestCenter, useDraggable, useDroppable, useSensor, useSensors, type DragEndEvent } from "@dnd-kit/core";
import { Users } from "lucide-react";

function StudentChip({ student }: { student: any }) { const { attributes, listeners, setNodeRef, transform, isDragging } = useDraggable({ id: `student-${student._id}` }); return <div ref={setNodeRef} style={transform ? { transform: `translate3d(${transform.x}px,${transform.y}px,0) scale(${isDragging ? 1.03 : 1}) rotate(${isDragging ? 1.5 : 0}deg)`, zIndex: isDragging ? 30 : undefined } : undefined} {...listeners} {...attributes} className="cursor-grab rounded-xl border border-slate-200 bg-white px-3 py-2 text-xs font-semibold text-slate-700 shadow-sm active:cursor-grabbing"><span className="font-mono text-slate-400">{student.admissionNo}</span><span className="ml-2">{student.firstName} {student.lastName}</span></div>; }
function Seat({ id, student, onClear }: { id: string; student?: any; onClear: () => void }) { const { setNodeRef, isOver } = useDroppable({ id }); return <div ref={setNodeRef} className={`flex min-h-20 flex-col justify-between rounded-2xl border p-3 transition-colors ${isOver ? "border-primary-300 bg-primary-50" : "border-slate-200 bg-slate-50"}`}>{student ? <><div><p className="text-[10px] font-bold uppercase tracking-wider text-slate-400">{id.replace("seat-", "Seat ")}</p><p className="mt-1 text-xs font-bold text-slate-800">{student.firstName} {student.lastName}</p></div><button type="button" onClick={onClear} className="self-end text-[10px] font-bold text-slate-400 hover:text-slate-700">Clear</button></> : <span className="text-center text-xs font-semibold text-slate-400">{id.replace("seat-", "Seat ")}</span>}</div>; }
export function SeatingPlanner({ students }: { students: any[] }) {
  const seats = Array.from({ length: Math.max(12, Math.min(30, students.length || 12)) }, (_, i) => `seat-${i + 1}`);
  const [assigned, setAssigned] = useState<Record<string, any>>({});
  const sensors = useSensors(useSensor(PointerSensor, { activationConstraint: { distance: 6 } }));
  const onDragEnd = (event: DragEndEvent) => { const studentId = String(event.active.id).replace("student-", ""); const seatId = String(event.over?.id || ""); const student = students.find((item) => item._id === studentId); if (student && seatId.startsWith("seat-")) setAssigned((state) => ({ ...state, [seatId]: student })); };
  const used = new Set(Object.values(assigned).map((item: any) => item._id));
  return <div className="space-y-5"><div className="flex items-center justify-between gap-4"><div><p className="text-[11px] font-bold uppercase tracking-[0.14em] text-primary-600">Exam seating</p><h3 className="mt-1 text-lg font-extrabold text-slate-950">Drag students into seats</h3><p className="mt-1 text-sm text-slate-500">A tactile seating canvas for planning room layouts before publication.</p></div><div className="flex items-center gap-2 rounded-xl bg-slate-100 px-3 py-2 text-xs font-bold text-slate-600"><Users className="h-4 w-4" />{used.size} placed</div></div><DndContext sensors={sensors} collisionDetection={closestCenter} onDragEnd={onDragEnd}><div className="grid gap-2 sm:grid-cols-2 lg:grid-cols-3">{seats.map((id) => <Seat key={id} id={id} student={assigned[id]} onClear={() => setAssigned((state) => { const next = { ...state }; delete next[id]; return next; })} />)}</div><div className="rounded-2xl border border-slate-200 bg-slate-50 p-4"><p className="text-xs font-bold uppercase tracking-wider text-slate-400">Unassigned roster</p><div className="mt-3 grid gap-2">{students.filter((student) => !used.has(student._id)).map((student) => <StudentChip key={student._id} student={student} />)}</div>{students.length === 0 && <p className="py-8 text-center text-sm text-slate-500">Choose a class to load the exam roster.</p>}</div></DndContext></div>;
}
