import { Types } from "mongoose";
import { PTMSession, Student, Teacher, Class } from "../models/index.js";
import { AppError } from "../utils/errors.js";
import { createAuditLog } from "./auditLog.js";
import { enqueueNotificationEvent } from "./notificationService.js";

function oid(id:string){return new Types.ObjectId(id)}
function day(d:Date){const x=new Date(d);x.setHours(0,0,0,0);return x} 
async function scopeTeachers(schoolId:string,ids:string[]){const n=await Teacher.countDocuments({_id:{$in:ids},schoolId,status:"active"});if(n!==ids.length)throw AppError.badRequest("All PTM teachers must be active teachers in this school");}
async function scopeClasses(schoolId:string,ids:string[]){const n=await Class.countDocuments({_id:{$in:ids},schoolId});if(n!==ids.length)throw AppError.badRequest("All PTM classes must belong to this school");}
export async function createPTM(schoolId:string,data:any,actorId:string){await scopeTeachers(schoolId,data.teacherIds);await scopeClasses(schoolId,data.classIds);const session=await PTMSession.create({...data,schoolId,date:day(data.date),createdBy:actorId});await createAuditLog({schoolId,userId:actorId,action:"CREATE",entity:"PTMSession",entityId:session.id,after:{title:session.title,date:session.date,status:session.status}});return session.toObject();}
export async function listPTMs(schoolId:string,q:any){const f:any={schoolId};if(q.date){const d=day(new Date(q.date));f.date={$gte:d,$lt:new Date(d.getTime()+86400000)}}if(q.status)f.status=q.status;return PTMSession.find(f).sort({date:1,startAt:1}).populate("classIds teacherIds","name firstName lastName employeeId").lean();}
export async function getPTM(schoolId:string,id:string){const s=await PTMSession.findOne({_id:id,schoolId}).populate("classIds teacherIds","name firstName lastName employeeId").lean();if(!s)throw AppError.notFound("PTM not found");return s;}
function slotEnd(start:Date,mins:number){return new Date(start.getTime()+mins*60000)}
export async function bookPTM(schoolId:string,id:string,data:any,actorId:string){const s=await PTMSession.findOne({_id:id,schoolId,status:"open"});if(!s)throw AppError.badRequest("PTM is not open for booking");const student=await Student.findOne({_id:data.studentId,schoolId,status:"active"}).select("_id parentIds classId userId").lean();if(!student)throw AppError.notFound("Student not found");if(!student.parentIds.some(p=>p.toString()===actorId))throw AppError.forbidden("Parent does not have access to this student");if(!s.teacherIds.some(t=>t.toString()===data.teacherId))throw AppError.badRequest("Teacher is not participating in this PTM");if(!s.classIds.some(c=>c.toString()===student.classId?.toString()))throw AppError.badRequest("Student class is not participating in this PTM");const start=new Date(data.startAt),end=slotEnd(start,s.slotMinutes);if(start<s.startAt||end>s.endAt)throw AppError.badRequest("Appointment is outside PTM hours");const conflict=s.appointments.some(a=>a.status!=="cancelled"&&new Date(a.startAt)<end&&new Date(a.endAt)>start&&(a.teacherId.toString()===data.teacherId||a.parentId.toString()===actorId));if(conflict)throw AppError.conflict("Teacher or parent already has an appointment in this time slot");s.appointments.push({parentId:oid(actorId),studentId:oid(data.studentId),teacherId:oid(data.teacherId),startAt:start,endAt:end,status:"booked",actionItems:[],createdAt:new Date()} as any);await s.save();await createAuditLog({schoolId,userId:actorId,action:"BOOK",entity:"PTMAppointment",entityId:s.appointments[s.appointments.length-1].id,after:{sessionId:id,studentId:data.studentId,teacherId:data.teacherId,startAt:start}});const teacher=await Teacher.findById(data.teacherId).select("userId").lean();if(teacher?.userId)await enqueueNotificationEvent({schoolId:oid(schoolId),eventType:"ptm.booked",category:"notices",priority:"normal",recipientIds:[teacher.userId],title:"PTM appointment booked",message:`A parent booked a PTM appointment at ${start.toISOString()}.`,idempotencyKey:`ptm:${id}:${s.appointments[s.appointments.length-1].id}`});return s.toObject();}
export async function updateAppointment(schoolId:string,id:string,appointmentId:string,data:any,actorId:string){const s=await PTMSession.findOne({_id:id,schoolId});if(!s)throw AppError.notFound("PTM not found");const a=s.appointments.id(appointmentId);if(!a)throw AppError.notFound("Appointment not found");const isParent=a.parentId.toString()===actorId;if(isParent&&data.status&&data.status!=="cancelled")throw AppError.forbidden("Parents may only cancel their appointment");if(data.status)a.status=data.status;if(data.notes!==undefined)a.notes=data.notes;if(data.actionItems!==undefined)a.actionItems=data.actionItems;s.markModified("appointments");await s.save();await createAuditLog({schoolId,userId:actorId,action:"UPDATE",entity:"PTMAppointment",entityId:appointmentId,after:{status:a.status,notes:a.notes}});return s.toObject();}
export async function openPTM(schoolId:string,id:string,actorId:string){const s=await PTMSession.findOneAndUpdate({_id:id,schoolId,status:"draft"},{status:"open"},{new:true});if(!s)throw AppError.badRequest("PTM is not in draft state");await createAuditLog({schoolId,userId:actorId,action:"OPEN",entity:"PTMSession",entityId:id,after:{status:"open"}});return s.toObject();}