import { Types } from "mongoose";
import { StudentBehaviour, Student } from "../models/index.js";
import { AppError } from "../utils/errors.js";
import { AuditLog } from "../models/index.js";

function id(value:string){if(!Types.ObjectId.isValid(value))throw AppError.badRequest("Invalid id");return new Types.ObjectId(value);}
async function student(schoolId:Types.ObjectId|string,studentId:string){const s=await Student.findOne({_id:id(studentId),schoolId}).select("_id classId sectionId parentIds").lean();if(!s)throw AppError.notFound("Student not found");return s;}
export async function createBehaviour(schoolId:string|Types.ObjectId,data:any,actorId:string){const s=await student(schoolId,data.studentId);const doc=await StudentBehaviour.create({...data,schoolId,studentId:s._id,createdBy:id(actorId)});await AuditLog.create({schoolId,actorId:id(actorId),action:"CREATE_STUDENT_BEHAVIOUR",resource:"StudentBehaviour",resourceId:doc._id,metadata:{kind:data.kind,severity:data.severity}});return doc;}
export async function listBehaviour(schoolId:string|Types.ObjectId,query:any){const filter:any={schoolId};if(query.studentId)filter.studentId=id(query.studentId);if(query.kind)filter.kind=query.kind;if(query.status)filter.status=query.status;if(query.from||query.to)filter.occurredAt={...(query.from?{$gte:query.from}:{}),...(query.to?{$lte:query.to}: {})};return StudentBehaviour.find(filter).sort({occurredAt:-1,createdAt:-1}).limit(query.limit||50).lean();}
export async function updateBehaviour(schoolId:string|Types.ObjectId,behaviourId:string,data:any,actorId:string){const doc=await StudentBehaviour.findOne({_id:id(behaviourId),schoolId});if(!doc)throw AppError.notFound("Behaviour record not found");if(data.status)doc.status=data.status;if(data.actionTaken!==undefined)doc.actionTaken=data.actionTaken;doc.updatedBy=id(actorId);if(data.status==="resolved"){doc.resolvedAt=new Date();doc.resolvedBy=id(actorId);}if(data.status&&data.status!=="resolved"){doc.resolvedAt=undefined;doc.resolvedBy=undefined;}await doc.save();await AuditLog.create({schoolId,actorId:id(actorId),action:"UPDATE_STUDENT_BEHAVIOUR",resource:"StudentBehaviour",resourceId:doc._id,metadata:{status:data.status}});return doc;}
export async function acknowledgeBehaviour(schoolId:string|Types.ObjectId,behaviourId:string,actorId:string){const doc=await StudentBehaviour.findOne({_id:id(behaviourId),schoolId});if(!doc)throw AppError.notFound("Behaviour record not found");const s=await student(schoolId,doc.studentId.toString());if(!s.parentIds?.some(p=>p.toString()===actorId))throw AppError.forbidden("You are not a parent of this student");doc.parentAcknowledgedAt=new Date();doc.parentAcknowledgedBy=id(actorId);await doc.save();return doc;}
export async function getBehaviour(schoolId:string|Types.ObjectId,behaviourId:string){const doc=await StudentBehaviour.findOne({_id:id(behaviourId),schoolId}).lean();if(!doc)throw AppError.notFound("Behaviour record not found");return doc;}
